import { randomUUID } from "node:crypto";
import { unlink } from "node:fs/promises";
import { createServer, type Server } from "node:net";
import type { CommandInvocationContext } from "@zhujun/agentloop";
import type { CredentialGrant, CredentialGrantRequest, DeviceCredentialEnvelope, IntegrationInvocationResponse, RuntimeConfigurationSnapshot, RuntimeTarget } from "../../../control-plane/contracts/index.ts";
import { LocalSecureEnvelopeStore } from "./local-secure-envelope-store.ts";

const PERMIT_TTL_MS = 30_000;
type Permit = { readonly invocationId: string; readonly context: CommandInvocationContext; readonly bindingId: string; readonly releaseId: string; readonly contentHash: string; readonly actions: readonly string[]; readonly expiresAt: number };

/** The envelope consumer is device-owned. It must not log or return credential material. */
export interface LocalIntegrationDeliveryPort {
  requestGrant(request: CredentialGrantRequest): Promise<CredentialGrant>;
  requestEnvelope(grant: CredentialGrant, request: CredentialGrantRequest): Promise<DeviceCredentialEnvelope>;
  invoke(envelope: DeviceCredentialEnvelope, request: CredentialGrantRequest, args: Readonly<Record<string, unknown>>): Promise<IntegrationInvocationResponse>;
}

/** Device-side analogue of the Cloud broker; its child protocol contains only an opaque permit. */
export class LocalIntegrationBroker {
  private readonly permits = new Map<string, Permit>();
  private server?: Server;
  private readonly input: { readonly target: RuntimeTarget; readonly snapshot: RuntimeConfigurationSnapshot; readonly delivery: LocalIntegrationDeliveryPort; readonly secureStore: LocalSecureEnvelopeStore; readonly socketPath: string; readonly now?: () => number };
  public constructor(input: { readonly target: RuntimeTarget; readonly snapshot: RuntimeConfigurationSnapshot; readonly delivery: LocalIntegrationDeliveryPort; readonly secureStore: LocalSecureEnvelopeStore; readonly socketPath: string; readonly now?: () => number }) { this.input = input; }
  async start(): Promise<void> { if (this.server !== undefined) return; await unlink(this.input.socketPath).catch((error: NodeJS.ErrnoException) => { if (error.code !== "ENOENT") throw error; }); this.server = createServer({ allowHalfOpen: true }, (socket) => { let source = ""; socket.setEncoding("utf8"); socket.on("data", (chunk: string) => { source += chunk; }); socket.on("end", () => { void this.respond(socket, source); }); }); await new Promise<void>((resolve, reject) => { this.server!.once("error", reject); this.server!.listen(this.input.socketPath, () => resolve()); }); }
  async close(): Promise<void> { const server = this.server; this.server = undefined; this.permits.clear(); if (server !== undefined) await new Promise<void>((resolve, reject) => server.close((error) => error === undefined ? resolve() : reject(error))); await unlink(this.input.socketPath).catch((error: NodeJS.ErrnoException) => { if (error.code !== "ENOENT") throw error; }); }
  commandEnvironment(context: CommandInvocationContext): Readonly<Record<string, string>> { const binding = this.input.snapshot.integrations.find((item) => item.integration === "enterprise_info"); if (binding === undefined || !entrypoint(context)) return {}; const now = this.now(); for (const [id, permit] of this.permits) if (permit.expiresAt <= now) this.permits.delete(id); const permit = randomUUID(); this.permits.set(permit, { invocationId: randomUUID(), context, bindingId: binding.bindingId, releaseId: binding.releaseId, contentHash: binding.contentHash, actions: binding.allowedActions ?? [], expiresAt: now + PERMIT_TTL_MS }); return { AGENTLOOP_INTEGRATION_BROKER_SOCKET: this.input.socketPath, AGENTLOOP_INTEGRATION_PERMIT: permit }; }
  private async respond(socket: import("node:net").Socket, source: string): Promise<void> { try { const request = parse(source); const permit = this.permits.get(request.permit); this.permits.delete(request.permit); if (permit === undefined || permit.expiresAt <= this.now() || !permit.actions.includes(request.action)) throw new Error("integration_not_authorized"); const invocation: CredentialGrantRequest = { contractVersion: "control-plane/v1", invocationId: permit.invocationId, runId: permit.context.runId, ...(permit.context.planId === undefined ? {} : { planId: permit.context.planId }), ...(permit.context.stepId === undefined ? {} : { stepId: permit.context.stepId }), integration: "enterprise_info", action: request.action, bindingId: permit.bindingId, releaseId: permit.releaseId, contentHash: permit.contentHash, skillNames: permit.context.skillNames, requestedAt: this.now() }; const grant = await this.input.delivery.requestGrant(invocation); const envelope = await this.input.delivery.requestEnvelope(grant, invocation); if (envelope.deviceId !== this.input.target.deviceId || envelope.grantId !== grant.grantId || envelope.expiresAt <= this.now()) throw new Error("credential_envelope_expired"); await this.input.secureStore.put(envelope); const response = await this.input.delivery.invoke(envelope, invocation, request.args); socket.end(JSON.stringify({ ok: true, result: response.result, receipt: response.receipt })); } catch (error) { const code = error instanceof Error && ["integration_not_authorized", "credential_grant_expired", "credential_envelope_expired", "integration_response_invalid"].includes(error.message) ? error.message : "integration_upstream_failed"; socket.end(JSON.stringify({ ok: false, code })); } }
  private now(): number { return (this.input.now ?? (() => Date.now()))(); }
}
function entrypoint(context: CommandInvocationContext): boolean { return context.skillNames.includes("enterprise-info") && (context.command === "python3" || context.command === "python") && context.args[0] === "scripts/enterprise_info.py"; }
function parse(source: string): { readonly permit: string; readonly action: string; readonly args: Readonly<Record<string, unknown>> } { try { const value = JSON.parse(source) as Record<string, unknown>; if (typeof value.permit !== "string" || typeof value.action !== "string" || value.args === null || typeof value.args !== "object" || Array.isArray(value.args)) throw new Error("integration_response_invalid"); return { permit: value.permit, action: value.action, args: value.args as Readonly<Record<string, unknown>> }; } catch (error) { if (error instanceof Error && error.message === "integration_response_invalid") throw error; throw new Error("integration_response_invalid"); } }
