import type { AdminMemberRole, AdminUserStatus, RuntimeTarget } from "../../../control-plane/contracts/index.ts";
import { AdminApiClient, AdminApiError } from "../shared/api/admin-api-client.ts";
import { renderAdminLoginPage } from "./login-page.ts";
import { bindAdminShell } from "./interaction-bindings.ts";
import { optionalProjection } from "./optional-projection.ts";
import { hasPermission, visibleNavigation, type Page } from "./navigation.ts";
import { renderPageContent } from "./page-content.ts";
import { escape, text } from "./page-helpers.ts";
import { modelCatalogNotice, parseModelInput } from "./pages/models-page.ts";
import { renderSidebarNavigation } from "./sidebar.ts";
import { createInitialUiState } from "./ui-state.ts";

/** The shell owns auth, projection refresh, shared layout, and operation callbacks.
 * Page markup is dispatched through page-content.ts and lives under pages/. */
const state = createInitialUiState();
export function bootAdminWeb(root: HTMLElement): void { void refresh(root); }
function api(): AdminApiClient { return new AdminApiClient(window.location.origin, window.fetch.bind(window), state.token === "" ? undefined : `Bearer ${state.token}`); }
function can(permission: Parameters<typeof hasPermission>[1]): boolean { return hasPermission(state.session, permission); }
function requestId(prefix: string): string { return `${prefix}:${crypto.randomUUID()}`; }

async function refresh(root: HTMLElement): Promise<void> {
  state.error = undefined;
  state.degradedErrors = [];
  try {
    await api().health();
    state.healthy = true;
    if (state.token !== "") {
      state.session = await api().session();
      const failures: string[] = [];
      [state.resources, state.releases, state.models, state.providers, state.skills, state.members, state.users, state.audit, state.runs, state.runtimes] = await Promise.all([
        optionalProjection("resources", () => can("release.read") ? api().resources() : Promise.resolve([]), state.resources, failures, messageFor), optionalProjection("releases", () => can("release.read") ? api().releases() : Promise.resolve([]), state.releases, failures, messageFor), optionalProjection("models", () => can("release.read") ? api().models() : Promise.resolve([]), state.models, failures, messageFor), optionalProjection("providers", () => can("release.read") ? api().providers() : Promise.resolve([]), state.providers, failures, messageFor), optionalProjection("Skills", () => can("skill.read") ? api().skills(state.skillPage, state.skills.pageSize) : Promise.resolve(state.skills), state.skills, failures, messageFor), Promise.resolve([]), optionalProjection("Admin users", () => can("user.read") ? api().users() : Promise.resolve([]), state.users, failures, messageFor), optionalProjection("audit", () => can("audit.read") ? api().auditEvents(50) : Promise.resolve(state.audit), state.audit, failures, messageFor), optionalProjection("Runs", () => can("trace.read") ? api().runs(state.runPage, state.runs.pageSize) : Promise.resolve(state.runs), state.runs, failures, messageFor), optionalProjection("Runtime instances", () => can("runtime.operate") ? api().runtimes(state.runtimePage, state.runtimes.pageSize) : Promise.resolve(state.runtimes), state.runtimes, failures, messageFor),
      ]);
      state.businessUsers = await optionalProjection("Business users", () => can("user.read") ? api().businessUsers() : Promise.resolve(state.businessUsers), state.businessUsers, failures, messageFor);
      state.degradedErrors = failures;
    } else state.session = undefined;
  } catch (error) { state.healthy = false; state.session = undefined; state.error = messageFor(error); }
  render(root);
}

function render(root: HTMLElement): void {
  if (state.session === undefined) { root.innerHTML = renderAdminLoginPage({ username: state.username, error: state.error }); bind(root); return; }
  const available = visibleNavigation(state.session);
  if (!available.some((item) => item.id === state.page)) state.page = "overview";
  const degraded = state.degradedErrors.length > 0 && (state.page === "traces" || state.page === "business-users" || state.page === "runtime") ? `<div class="degraded-notice" role="status"><strong>Router 数据暂不可用</strong><span>${escape(state.degradedErrors.join("；"))}</span></div>` : "";
  root.innerHTML = `<div class="admin-shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">A</span><span>AgentLoop</span></div><p class="workspace-label">管理控制面</p><nav class="nav" aria-label="管理模块">${renderSidebarNavigation(available, state.page)}</nav><div class="sidebar-footer"><span class="status-dot ${state.healthy ? "ok" : "off"}"></span>${state.healthy ? "Admin API 已连接" : "等待 Admin API 连接"}</div></aside><section class="workspace"><header class="topbar"><div><p class="eyebrow">${pageTitle(state.page)}</p><h1>${pageHeading(state.page)}</h1></div></header><main class="content content-${state.page}">${degraded}${state.error === undefined ? renderPageContent(state.page, { state, can }) : connectionError()}</main></section></div>${state.notice === undefined ? "" : `<div class="toast">${escape(state.notice)}</div>`}`;
  bind(root);
}

function bind(root: HTMLElement): void { bindAdminShell(root, { state, render, login, saveModel, saveProvider, setDefaultProvider, deleteModel, selectSkill, changeSkillPage, selectRun, changeRunPage, createMember, saveAdminUser, transitionAdminUser, changeAdminUserPage, runtimeRowOperation, changeRuntimePage, traceRun, transitionMember, suspendBusinessUser, resetBusinessPassword }); }
async function createMember(event: SubmitEvent, root: HTMLElement): Promise<void> { event.preventDefault(); try { const data = new FormData(event.currentTarget as HTMLFormElement); const now = Date.now(); await api().createMember({ contractVersion: "control-plane/v1", memberId: `member-${crypto.randomUUID()}`, scopeId: text(data, "scopeId"), subject: text(data, "subject"), displayName: text(data, "displayName"), role: text(data, "role") as AdminMemberRole, status: "active", revision: 1, createdAt: now, updatedAt: now }, 0, requestId("member-create")); state.notice = "成员已创建"; await refresh(root); } catch (error) { fail(root, error); } }
async function saveAdminUser(event: SubmitEvent, root: HTMLElement): Promise<void> { event.preventDefault(); try { const data = new FormData(event.currentTarget as HTMLFormElement); const password = text(data, "password"); const editing = state.userEditingId === undefined ? undefined : state.users.find((user) => user.userId === state.userEditingId); if (editing === undefined) { const now = Date.now(); await api().createUser({ contractVersion: "control-plane/v1", userId: `admin-user-${crypto.randomUUID()}`, username: text(data, "username"), displayName: text(data, "displayName"), ...(text(data, "scopeId") === "" ? {} : { scopeId: text(data, "scopeId") }), role: text(data, "role") as AdminMemberRole, status: "active", revision: 1, createdAt: now, updatedAt: now }, password, requestId("admin-user-create")); } else { await api().updateUser(editing.userId, { displayName: text(data, "displayName"), ...(text(data, "scopeId") === "" ? {} : { scopeId: text(data, "scopeId") }), role: text(data, "role") as AdminMemberRole, expectedRevision: editing.revision }, requestId("admin-user-update")); if (password !== "") await api().resetUserPassword(editing.userId, password, editing.revision + 1, requestId("admin-user-password")); } state.userEditingId = undefined; state.userModal = false; state.notice = "管理端用户已保存"; await refresh(root); } catch (error) { fail(root, error); } }
async function transitionAdminUser(button: HTMLElement, root: HTMLElement): Promise<void> { try { await api().transitionUser(button.dataset.userTransition!, button.dataset.userStatus as AdminUserStatus, Number(button.dataset.userRevision), requestId("admin-user-transition")); state.notice = "管理端用户状态已更新"; await refresh(root); } catch (error) { fail(root, error); } }
function changeAdminUserPage(page: number, root: HTMLElement): void { const pageCount = Math.max(1, Math.ceil(state.users.length / state.userPageSize)); if (page < 1 || page > pageCount) return; state.userPage = page; render(root); }
async function transitionMember(button: HTMLElement, root: HTMLElement): Promise<void> { try { await api().transitionMember(button.dataset.memberTransition!, button.dataset.memberState as "active" | "suspended", Number(button.dataset.memberRevision), requestId("member-transition")); state.notice = "成员状态已更新"; await refresh(root); } catch (error) { fail(root, error); } }
async function suspendBusinessUser(id: string, root: HTMLElement): Promise<void> { try { await api().suspendBusinessUser(id); state.notice = "业务用户已停用，现有会话已撤销"; await refresh(root); } catch (error) { fail(root, error); } }
async function resetBusinessPassword(event: SubmitEvent, root: HTMLElement): Promise<void> { event.preventDefault(); if (state.businessUserPasswordId === undefined) return; try { const password = text(new FormData(event.currentTarget as HTMLFormElement), "password"); await api().resetBusinessUserPassword(state.businessUserPasswordId, password); state.businessUserPasswordId = undefined; state.notice = "业务用户密码已重置"; await refresh(root); } catch (error) { fail(root, error); } }
async function changeRuntimePage(page: number, root: HTMLElement): Promise<void> { if (page < 1 || page > state.runtimes.pageCount) return; state.runtimePage = page; try { state.runtimes = await api().runtimes(page, state.runtimes.pageSize); render(root); } catch (error) { fail(root, error); } }
async function runtimeRowOperation(button: HTMLElement, root: HTMLElement): Promise<void> { const runtime = state.runtimes.items.find((item) => item.id === button.dataset.runtimeId); const operation = button.dataset.runtimeOperation as "drain" | "recover" | "restart" | undefined; if (runtime === undefined || operation === undefined || runtime.plane === "local") return; if (!window.confirm(`确认对 Runtime ${runtime.displayName ?? runtime.id} 执行 ${operation}？`)) return; try { const result = await api().runtimeOperation(runtime.id, operation, { plane: "cloud", scopeId: runtime.scopeId ?? state.scopeId, runtimeId: runtime.id, runtimeClass: runtime.profile } satisfies RuntimeTarget, 0, requestId(`runtime-${operation}`)); state.notice = `${result.runtimeId} 已进入 ${result.state}`; await refresh(root); } catch (error) { fail(root, error); } }
async function traceRun(event: SubmitEvent, root: HTMLElement): Promise<void> { event.preventDefault(); const output = root.querySelector<HTMLElement>("#trace-result"); try { const trace = await api().trace(text(new FormData(event.currentTarget as HTMLFormElement), "runId")); if (output !== null) output.innerHTML = `<div class="trace-summary"><strong>${escape(trace.runId)}</strong>${trace.target === undefined ? "" : `<span>${escape(trace.target.plane)} · ${escape(trace.target.scopeId)} · ${escape(trace.target.runtimeId)}</span>`}</div><div class="trace-columns"><div><p>已记录事实</p>${trace.facts.length === 0 ? "<em>无</em>" : trace.facts.map((fact) => `<div class="fact"><b>${escape(fact.source)}</b><span>${escape(fact.kind)}</span><code>${escape(fact.ref)}</code></div>`).join("")}</div><div><p>缺失边界</p>${trace.missingBoundaries.length === 0 ? "<em>无</em>" : trace.missingBoundaries.map((item) => `<div class="fact missing"><b>${escape(item.source)}</b><span>${escape(item.reason)}</span></div>`).join("")}</div></div>`; } catch (error) { if (output !== null) output.textContent = messageFor(error); } }
async function saveModel(event: SubmitEvent, root: HTMLElement): Promise<void> { event.preventDefault(); try { const data = new FormData(event.currentTarget as HTMLFormElement); const model = parseModelInput(data, state.providers); const current = state.modelEditingKey === undefined ? undefined : state.models.find((item) => item.key === state.modelEditingKey); const result = current === undefined ? await api().registerModel(model, requestId("model-register")) : await api().updateModel(current.key, model, requestId("model-update")); state.modelEditingKey = undefined; state.modelProviderKey = undefined; state.modelModal = false; state.notice = modelCatalogNotice(result, "模型"); await refresh(root); } catch (error) { fail(root, error); } }
async function saveProvider(event: SubmitEvent, root: HTMLElement): Promise<void> { event.preventDefault(); try { const data = new FormData(event.currentTarget as HTMLFormElement); const apiKey = text(data, "apiKey"); const result = await api().registerProvider({ providerKey: text(data, "providerKey"), baseUrl: text(data, "baseUrl"), ...(apiKey === "" ? {} : { apiKey }), protocol: text(data, "protocol") as "chat-completions" | "responses", defaultProvider: data.get("defaultProvider") === "on" }, requestId("provider-register")); state.providerEditingKey = undefined; state.providerModal = false; state.notice = modelCatalogNotice(result, "Provider"); await refresh(root); } catch (error) { fail(root, error); } }
async function setDefaultProvider(providerKey: string, root: HTMLElement): Promise<void> { try { const result = await api().setDefaultProvider(providerKey, requestId("provider-default")); state.notice = modelCatalogNotice(result, "默认 Provider"); await refresh(root); } catch (error) { fail(root, error); } }
async function deleteModel(modelKey: string, root: HTMLElement): Promise<void> { try { const result = await api().deleteModel(modelKey, requestId("model-delete")); state.notice = modelCatalogNotice(result, "模型"); await refresh(root); } catch (error) { fail(root, error); } }
async function selectSkill(name: string, root: HTMLElement): Promise<void> { try { state.skillDetail = await api().skill(name); state.page = "skills"; render(root); } catch (error) { fail(root, error); } }
async function changeSkillPage(page: number, root: HTMLElement): Promise<void> { if (page < 1 || page > state.skills.pageCount) return; state.skillPage = page; try { state.skills = await api().skills(page, state.skills.pageSize); state.skillDetail = undefined; render(root); } catch (error) { fail(root, error); } }
async function selectRun(id: string, root: HTMLElement): Promise<void> { try { state.runDetail = await api().run(id); state.page = "traces"; render(root); } catch (error) { fail(root, error); } }
async function changeRunPage(page: number, root: HTMLElement): Promise<void> { if (page < 1 || page > state.runs.pageCount) return; state.runPage = page; try { state.runs = await api().runs(page, state.runs.pageSize); state.runDetail = undefined; render(root); } catch (error) { fail(root, error); } }
function fail(root: HTMLElement, error: unknown): void { state.error = messageFor(error); render(root); }
async function login(event: SubmitEvent, root: HTMLElement): Promise<void> { event.preventDefault(); try { const data = new FormData(event.currentTarget as HTMLFormElement); const username = text(data, "username"); const requestedScope = text(data, "scopeId"); const session = await new AdminApiClient(window.location.origin, window.fetch.bind(window)).login(username, text(data, "password")); state.username = username; state.token = session.accessToken; if (requestedScope !== "") state.scopeId = requestedScope; localStorage.setItem("agentloop.admin.token", state.token); localStorage.setItem("agentloop.admin.username", state.username); localStorage.setItem("agentloop.admin.scope", state.scopeId); state.notice = "登录成功"; await refresh(root); } catch (error) { fail(root, error); } }

function connectionError(): string { return `<section class="error-wrap"><article class="panel error-panel"><p class="eyebrow">管理端不可用</p><h2>无法建立管理会话</h2><p>${escape(state.error ?? "未知错误")}</p><button class="primary" data-page="overview">返回总览</button></article></section>`; }
function pageTitle(page: Page): string { return ({ overview: "CONTROL PLANE", models: "MODEL CATALOG", skills: "SKILL OPERATIONS", "admin-users": "ADMINISTRATION", "business-users": "BUSINESS OPERATIONS", runtime: "RUNTIME OPERATIONS", traces: "TASK TRACKING", audit: "AUDIT" })[page]; }
function pageHeading(page: Page): string { return ({ overview: "管理概览", models: "模型管理", skills: "Skill 运营", "admin-users": "管理端用户", "business-users": "业务端用户", runtime: "Runtime 运维", traces: "任务跟踪", audit: "审计记录" })[page]; }
function messageFor(error: unknown): string { return error instanceof AdminApiError ? `${error.status}${error.code === undefined ? "" : ` · ${error.code}`}` : error instanceof Error ? error.message : "未知错误"; }
