import type { AdminMember, AdminMemberRole, ControlPlaneResource, ReleaseState, ResourceKind, ResourceRelease, RolloutState, RuntimeTarget } from "../../../control-plane/contracts/index.ts";
import { AdminApiClient, AdminApiError, type AdminSession } from "../shared/api/admin-api-client.ts";
import { hasPermission, navigationItems, visibleNavigation, type Page } from "./navigation.ts";

type AuditRow = { eventId: string; actorId: string; action: string; resourceId: string; releaseId?: string; createdAt: number };
type UiState = { page: Page; token: string; username: string; scopeId: string; session?: AdminSession; healthy?: boolean; resources: readonly ControlPlaneResource[]; releases: readonly ResourceRelease[]; members: readonly AdminMember[]; audit: readonly AuditRow[]; error?: string; notice?: string; assignmentReleaseId?: string };

const state: UiState = { page: "overview", token: localStorage.getItem("agentloop.admin.token") ?? "", username: localStorage.getItem("agentloop.admin.username") ?? "", scopeId: localStorage.getItem("agentloop.admin.scope") ?? "platform", resources: [], releases: [], members: [], audit: [] };
export function bootAdminWeb(root: HTMLElement): void { void refresh(root); }
function api(): AdminApiClient { return new AdminApiClient(window.location.origin, window.fetch.bind(window), state.token === "" ? undefined : `Bearer ${state.token}`); }
function can(permission: Parameters<typeof hasPermission>[1]): boolean { return hasPermission(state.session, permission); }
function requestId(prefix: string): string { return `${prefix}:${crypto.randomUUID()}`; }

async function refresh(root: HTMLElement): Promise<void> {
  state.error = undefined;
  try {
    state.healthy = (await api().health()).status === "ok";
    if (state.token !== "") {
      state.session = await api().session();
      [state.resources, state.releases, state.members, state.audit] = await Promise.all([
        can("release.read") ? api().resources() : Promise.resolve([]), can("release.read") ? api().releases() : Promise.resolve([]), can("member.read") ? api().members(state.scopeId) : Promise.resolve([]), can("audit.read") ? api().auditEvents(50) : Promise.resolve([]),
      ]);
    } else state.session = undefined;
  } catch (error) { state.healthy = false; state.session = undefined; state.error = messageFor(error); }
  render(root);
}

function render(root: HTMLElement): void {
  const available = visibleNavigation(state.session);
  if (!available.some((item) => item.id === state.page)) state.page = "overview";
  root.innerHTML = `<div class="admin-shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">A</span><span>AgentLoop</span></div><p class="workspace-label">管理控制面</p><nav class="nav" aria-label="管理模块">${available.map((item) => `<button class="nav-item ${state.page === item.id ? "active" : ""}" data-page="${item.id}"><span>${item.icon}</span>${item.label}</button>`).join("")}</nav><div class="sidebar-footer"><span class="status-dot ${state.healthy ? "ok" : "off"}"></span>${state.healthy ? "Admin API 已连接" : "等待 Admin API 连接"}</div></aside><section class="workspace"><header class="topbar"><div><p class="eyebrow">${pageTitle(state.page)}</p><h1>${pageHeading(state.page)}</h1></div><div class="top-actions"><button class="ghost" data-action="refresh">刷新</button><button class="identity" data-page="settings">${state.session === undefined ? "配置访问" : `${escape(state.session.role)} · ${escape(state.session.actorId)}`}</button></div></header><main class="content">${state.error === undefined ? pageContent() : connectionError()}</main></section></div>${state.notice === undefined ? "" : `<div class="toast">${escape(state.notice)}</div>`}`;
  bind(root);
}

function pageContent(): string { if (state.session === undefined) return settingsPage(true); switch (state.page) { case "overview": return overviewPage(); case "releases": return catalogPage(); case "skills": return catalogPage("skill"); case "members": return membersPage(); case "runtime": return runtimePage(); case "traces": return tracesPage(); case "audit": return auditPage(); case "settings": return settingsPage(false); } }
function overviewPage(): string { const active = state.releases.filter((release) => release.state === "active").length; const skills = state.releases.filter((release) => release.kind === "skill").length; return `<section class="metric-grid">${metric("已发布资源", state.resources.length, "含版本与并发修订")}${metric("生效 Release", active, "状态为 active")}${metric("Skill Release", skills, "受独立 Skill 权限约束")}${metric("活跃成员", state.members.filter((member) => member.status === "active").length, "当前 scope")}</section><section class="two-column"><article class="panel"><div class="panel-title"><div><p>最近配置变更</p><span>来自不可变审计事件</span></div><button class="text-button" data-page="audit">查看全部</button></div>${auditRows(state.audit.slice(0, 5))}</article><article class="panel"><div class="panel-title"><div><p>运维工作台</p><span>按权限开放入口</span></div></div><div class="quick-actions">${can("release.write") ? quick("配置发布", "新建不可变 Release", "releases") : ""}${can("skill.write") ? quick("Skill 运营", "查看并发布 Skill Release", "skills") : ""}${can("runtime.operate") ? quick("Runtime 运维", "执行 drain 或 recover", "runtime") : ""}${can("trace.read") ? quick("任务追踪", "查询 Run 的跨边界事实", "traces") : ""}</div></article></section>`; }

function catalogPage(kind?: ResourceKind): string { const releases = state.releases.filter((release) => kind === undefined || release.kind === kind); const writable = kind === "skill" ? can("skill.write") : can("release.write"); return `<section class="page-grid"><article class="panel wide"><div class="panel-title"><div><p>${kind === "skill" ? "Skill Release" : "配置 Release"}</p><span>Release 内容不可变；状态迁移和 Target Assignment 使用资源 revision 防并发覆盖。</span></div><span class="count">${releases.length}</span></div><div class="table-wrap"><table><thead><tr><th>资源 / Release</th><th>类型</th><th>版本</th><th>状态</th><th>内容摘要</th><th></th></tr></thead><tbody>${releases.length === 0 ? emptyRow(6, "暂无 Release。可以先创建 draft。") : releases.map(releaseRow).join("")}</tbody></table></div></article>${writable ? releaseForm(kind) : permissionNote("当前角色仅有读取权限；发布操作由 release.write 或 skill.write 控制。")}</section>${state.assignmentReleaseId === undefined ? "" : assignmentForm(state.assignmentReleaseId)}`; }
function releaseForm(kind?: ResourceKind): string { const defaultKind = kind ?? "policy"; return `<article class="panel form-panel"><div class="panel-title"><div><p>新建 Draft</p><span>浏览器计算 SHA-256；凭据不进入 Release payload。</span></div></div><form id="release-form" class="form-grid"><label>类型<select name="kind">${["model_route", "integration", "skill", "policy"].filter((value) => kind === undefined || value === kind).map((value) => `<option value="${value}" ${value === defaultKind ? "selected" : ""}>${labelForKind(value as ResourceKind)}</option>`).join("")}</select></label><label>资源 ID<input name="resourceId" required placeholder="例如 policy-default"></label><label>Release ID<input name="releaseId" required placeholder="例如 rel-policy-001"></label><label>版本号<input name="version" type="number" min="1" value="1" required></label><label>Schema version<input name="schemaVersion" value="${defaultKind}/v1" required></label><label class="span-2">公开 Payload JSON<textarea name="payload" rows="7" required>{}</textarea></label><p class="form-help span-2">已有资源使用当前 revision；新资源使用 revision 0。发布后仍需状态迁移和 Target Assignment 才会影响 Runtime。</p><button class="primary span-2" type="submit">创建不可变 Draft</button></form></article>`; }
function assignmentForm(releaseId: string): string { const release = state.releases.find((item) => item.releaseId === releaseId); if (release === undefined) return ""; return `<section class="dialog-backdrop"><article class="dialog"><button class="dialog-close" data-action="close-assignment" aria-label="关闭">×</button><p class="eyebrow">TARGET ASSIGNMENT</p><h2>分配 ${escape(release.releaseId)}</h2><p>只创建目标分配；是否生效由 rollout 状态与 Release 状态共同决定。</p><form id="assignment-form" class="form-grid"><input type="hidden" name="releaseId" value="${escape(release.releaseId)}"><label>执行平面<select name="plane"><option value="cloud">Cloud</option><option value="local">Local</option><option value="both">Cloud + Local</option></select></label><label>目标层级<select name="targetKind"><option value="platform">平台默认</option><option value="tenant">Scope</option><option value="runtime_class">Runtime class</option><option value="runtime_id">Runtime ID</option><option value="device_id">Device ID（仅 Local）</option></select></label><label>Scope ID<input name="scopeId" placeholder="platform 或业务 scope"></label><label>Runtime class<input name="runtimeClass"></label><label>Runtime ID<input name="runtimeId"></label><label>Device ID<input name="deviceId"></label><label>优先级<input name="priority" type="number" value="10" required></label><label>Rollout<select name="rolloutState"><option value="planned">planned</option><option value="observe">observe</option><option value="canary">canary</option><option value="active">active</option><option value="suspended">suspended</option></select></label><button class="primary span-2" type="submit">创建 Target Assignment</button></form></article></section>`; }

function membersPage(): string { return `<section class="page-grid"><article class="panel wide"><div class="panel-title"><div><p>成员与授权</p><span>角色决定 API 有效权限；前端仅按会话权限呈现可操作界面。</span></div><span class="tag">scope: ${escape(state.scopeId)}</span></div><div class="table-wrap"><table><thead><tr><th>成员</th><th>角色</th><th>状态</th><th>Revision</th><th></th></tr></thead><tbody>${state.members.length === 0 ? emptyRow(5, "该 scope 暂无成员") : state.members.map(memberRow).join("")}</tbody></table></div></article>${can("member.write") ? memberForm() : permissionNote("当前角色不能创建成员或变更成员状态。")}</section>`; }
function memberForm(): string { return `<article class="panel form-panel"><div class="panel-title"><div><p>添加成员</p><span>角色是管理端权限的来源，不绑定 Router 用户会话。</span></div></div><form id="member-form" class="form-grid"><label>Subject<input name="subject" required placeholder="例如 ops@example.com"></label><label>显示名称<input name="displayName" required placeholder="例如 运维同学"></label><label>Scope ID<input name="scopeId" value="${escape(state.scopeId)}" required></label><label>角色<select name="role">${roleOptions()}</select></label><button class="primary span-2" type="submit">创建成员</button></form></article>`; }
function runtimePage(): string { return `<section class="page-grid"><article class="panel wide"><div class="panel-title"><div><p>Runtime 运维</p><span>操作需要明确 Runtime target 与 expected revision；不会通过全局 RunService 热更新。</span></div></div><form id="runtime-form" class="form-grid"><label>Runtime ID<input name="runtimeId" required></label><label>Scope ID<input name="scopeId" value="${escape(state.scopeId)}" required></label><label>Plane<select name="plane"><option value="cloud">Cloud</option><option value="local">Local</option></select></label><label>Runtime class<input name="runtimeClass"></label><label>Device ID<input name="deviceId"></label><label>Expected revision<input name="expectedRevision" type="number" min="0" value="0" required></label><div class="span-2 button-row"><button class="danger" type="submit" name="operation" value="drain">Drain Runtime</button><button class="secondary" type="submit" name="operation" value="recover">Recover Runtime</button></div></form></article><article class="panel"><p class="panel-kicker">当前边界</p><h3>没有伪造 Runtime 清单</h3><p>当前 API 只提供受保护的 drain/recover 操作。Runtime 清单读模型需要由 Router/Host 提供只读运维投影后再接入。</p></article></section>`; }
function tracesPage(): string { return `<section class="page-grid"><article class="panel wide"><div class="panel-title"><div><p>Run 追踪</p><span>只展示 Router、Runtime、Control Plane 已记录的事实与缺失边界。</span></div></div><form id="trace-form" class="inline-form"><input name="runId" required placeholder="输入 Run ID，例如 run_xxx"><button class="primary" type="submit">查询追踪</button></form><div id="trace-result" class="trace-result">尚未查询 Run。</div></article><article class="panel"><p class="panel-kicker">证据边界</p><h3>追踪不是猜测</h3><p>未记录、未授权或不可用的边界会被明确标注，而不会用页面状态推断任务完成。</p></article></section>`; }
function auditPage(): string { return `<section class="panel"><div class="panel-title"><div><p>审计记录</p><span>不可变操作事实，按记录时间倒序。</span></div><span class="count">${state.audit.length}</span></div>${auditRows(state.audit)}</section>`; }
function settingsPage(required: boolean): string { return `<section class="settings-wrap"><article class="panel settings"><p class="eyebrow">独立 Admin API 会话</p><h2>${required ? "登录管理控制面" : "连接与会话"}</h2><p>使用管理端用户名和密码登录。密码只提交给 Admin API 的登录接口；浏览器仅保存短期会话令牌，不连接数据库。</p><form id="settings-form" class="form-grid"><label class="span-2">用户名<input name="username" value="${escape(state.username)}" autocomplete="username" required placeholder="例如 admin"></label><label class="span-2">密码<input name="password" type="password" autocomplete="current-password" required placeholder="输入管理端密码"></label><label>默认 Scope ID<input name="scopeId" value="${escape(state.scopeId)}" required></label><label>会话状态<input value="${state.session === undefined ? "尚未登录" : `${state.session.role} · ${state.session.actorId}`}" disabled></label><button class="primary span-2" type="submit">登录并进入管理端</button></form>${state.session === undefined ? "" : `<button class="text-button" data-action="sign-out">退出当前会话</button>`}</article></section>`; }
function connectionError(): string { return `<section class="settings-wrap"><article class="panel settings"><p class="eyebrow">连接失败</p><h2>无法建立管理会话</h2><p>${escape(state.error ?? "未知错误")}</p><button class="primary" data-page="settings">检查连接设置</button></article></section>`; }

function releaseRow(release: ResourceRelease): string { const next = nextReleaseState(release.state); const resource = state.resources.find((item) => item.resourceId === release.resourceId); const writable = release.kind === "skill" ? can("skill.write") : can("release.write"); return `<tr><td><strong>${escape(release.resourceId)}</strong><small>${escape(release.releaseId)}</small></td><td><span class="tag purple">${labelForKind(release.kind)}</span></td><td>v${release.version}<small>资源 rev ${resource?.revision ?? "—"}</small></td><td>${statusPill(release.state)}</td><td><code>${escape(release.contentHash.slice(0, 12))}…</code><small>${formatTime(release.createdAt)}</small></td><td class="actions">${writable && next !== undefined ? `<button class="text-button" data-transition="${escape(release.releaseId)}" data-next-state="${next}">→ ${next}</button>` : ""}${writable ? `<button class="text-button" data-assignment="${escape(release.releaseId)}">分配目标</button>` : ""}</td></tr>`; }
function memberRow(member: AdminMember): string { const next = member.status === "active" ? "suspended" : member.status === "suspended" || member.status === "invited" ? "active" : undefined; return `<tr><td><strong>${escape(member.displayName)}</strong><small>${escape(member.subject)}</small></td><td><span class="tag">${escape(member.role)}</span></td><td>${statusPill(member.status)}</td><td>${member.revision}</td><td class="actions">${can("member.write") && next !== undefined ? `<button class="text-button" data-member-transition="${escape(member.memberId)}" data-member-state="${next}" data-member-revision="${member.revision}">${next === "active" ? "启用" : "暂停"}</button>` : ""}</td></tr>`; }
function auditRows(events: readonly AuditRow[]): string { return events.length === 0 ? `<div class="empty">暂无审计记录</div>` : `<div class="activity">${events.map((event) => `<div class="activity-row"><span class="activity-dot"></span><div><strong>${escape(event.action)}</strong><p>${escape(event.actorId)} · ${escape(event.resourceId)}${event.releaseId === undefined ? "" : ` · ${escape(event.releaseId)}`}</p></div><time>${formatTime(event.createdAt)}</time></div>`).join("")}</div>`; }

function bind(root: HTMLElement): void {
  root.querySelectorAll<HTMLElement>("[data-page]").forEach((button) => button.addEventListener("click", () => { state.page = button.dataset.page as Page; state.error = undefined; render(root); }));
  root.querySelector<HTMLElement>("[data-action=refresh]")?.addEventListener("click", () => void refresh(root));
  root.querySelector<HTMLElement>("[data-action=sign-out]")?.addEventListener("click", () => { localStorage.removeItem("agentloop.admin.token"); state.token = ""; state.session = undefined; state.notice = "本机令牌已清除"; render(root); });
  root.querySelector<HTMLElement>("[data-action=close-assignment]")?.addEventListener("click", () => { state.assignmentReleaseId = undefined; render(root); });
  root.querySelector<HTMLFormElement>("#settings-form")?.addEventListener("submit", (event) => void login(event, root));
  root.querySelector<HTMLFormElement>("#member-form")?.addEventListener("submit", (event) => void createMember(event, root));
  root.querySelector<HTMLFormElement>("#release-form")?.addEventListener("submit", (event) => void createRelease(event, root));
  root.querySelector<HTMLFormElement>("#assignment-form")?.addEventListener("submit", (event) => void createAssignment(event, root));
  root.querySelector<HTMLFormElement>("#runtime-form")?.addEventListener("submit", (event) => void runtimeOperation(event, root));
  root.querySelector<HTMLFormElement>("#trace-form")?.addEventListener("submit", (event) => void traceRun(event, root));
  root.querySelectorAll<HTMLElement>("[data-transition]").forEach((button) => button.addEventListener("click", () => void transitionRelease(button, root)));
  root.querySelectorAll<HTMLElement>("[data-assignment]").forEach((button) => button.addEventListener("click", () => { state.assignmentReleaseId = button.dataset.assignment; render(root); }));
  root.querySelectorAll<HTMLElement>("[data-member-transition]").forEach((button) => button.addEventListener("click", () => void transitionMember(button, root)));
}

async function createMember(event: SubmitEvent, root: HTMLElement): Promise<void> { event.preventDefault(); try { const data = new FormData(event.currentTarget as HTMLFormElement); const now = Date.now(); await api().createMember({ contractVersion: "control-plane/v1", memberId: `member-${crypto.randomUUID()}`, scopeId: text(data, "scopeId"), subject: text(data, "subject"), displayName: text(data, "displayName"), role: text(data, "role") as AdminMemberRole, status: "active", revision: 1, createdAt: now, updatedAt: now }, 0, requestId("member-create")); state.notice = "成员已创建"; await refresh(root); } catch (error) { fail(root, error); } }
async function createRelease(event: SubmitEvent, root: HTMLElement): Promise<void> { event.preventDefault(); try { const data = new FormData(event.currentTarget as HTMLFormElement); const kind = text(data, "kind") as ResourceKind; const payload = JSON.parse(text(data, "payload")) as Record<string, unknown>; const resourceId = text(data, "resourceId"); const release = { contractVersion: "control-plane/v1" as const, resourceId, releaseId: text(data, "releaseId"), version: Number(text(data, "version")), kind, schemaVersion: text(data, "schemaVersion"), contentHash: await contentHash(kind, text(data, "schemaVersion"), payload), authorId: state.session!.actorId, createdAt: Date.now(), state: "draft" as const, payload }; await api().publishRelease({ release, expectedRevision: state.resources.find((item) => item.resourceId === resourceId)?.revision ?? 0 }, requestId("release-publish")); state.notice = "Draft 已创建"; await refresh(root); } catch (error) { fail(root, error); } }
async function transitionRelease(button: HTMLElement, root: HTMLElement): Promise<void> { try { const release = state.releases.find((item) => item.releaseId === button.dataset.transition); if (release === undefined) throw new Error("Release 已不在当前视图中"); const revision = state.resources.find((item) => item.resourceId === release.resourceId)?.revision; if (revision === undefined) throw new Error("缺少资源 revision，请刷新后重试"); await api().transitionRelease(release.releaseId, { state: button.dataset.nextState as ReleaseState, expectedRevision: revision }, requestId("release-transition")); state.notice = `Release 已迁移至 ${button.dataset.nextState}`; await refresh(root); } catch (error) { fail(root, error); } }
async function createAssignment(event: SubmitEvent, root: HTMLElement): Promise<void> { event.preventDefault(); try { const data = new FormData(event.currentTarget as HTMLFormElement); const release = state.releases.find((item) => item.releaseId === text(data, "releaseId")); if (release === undefined) throw new Error("Release 不存在"); const revision = state.resources.find((item) => item.resourceId === release.resourceId)?.revision; if (revision === undefined) throw new Error("缺少资源 revision，请刷新后重试"); const kind = text(data, "targetKind"); const scopeId = text(data, "scopeId"); const target = kind === "platform" ? { kind: "platform" as const } : kind === "tenant" ? { kind: "tenant" as const, scopeId } : kind === "runtime_class" ? { kind: "runtime_class" as const, scopeId, runtimeClass: text(data, "runtimeClass") } : kind === "runtime_id" ? { kind: "runtime_id" as const, scopeId, runtimeId: text(data, "runtimeId") } : { kind: "device_id" as const, scopeId, deviceId: text(data, "deviceId") }; await api().createTargetAssignment({ expectedRevision: revision, assignment: { contractVersion: "control-plane/v1", assignmentId: `assignment-${crypto.randomUUID()}`, resourceId: release.resourceId, releaseId: release.releaseId, scope: { plane: text(data, "plane") as "cloud" | "local" | "both", target }, priority: Number(text(data, "priority")), rolloutState: text(data, "rolloutState") as RolloutState, revision: 1 } }, requestId("target-assignment")); state.assignmentReleaseId = undefined; state.notice = "Target Assignment 已创建"; await refresh(root); } catch (error) { fail(root, error); } }
async function transitionMember(button: HTMLElement, root: HTMLElement): Promise<void> { try { await api().transitionMember(button.dataset.memberTransition!, button.dataset.memberState as "active" | "suspended", Number(button.dataset.memberRevision), requestId("member-transition")); state.notice = "成员状态已更新"; await refresh(root); } catch (error) { fail(root, error); } }
async function runtimeOperation(event: SubmitEvent, root: HTMLElement): Promise<void> { event.preventDefault(); try { const data = new FormData(event.currentTarget as HTMLFormElement); const operation = (event.submitter as HTMLButtonElement | null)?.value as "drain" | "recover"; const runtimeId = text(data, "runtimeId"); const target: RuntimeTarget = { plane: text(data, "plane") as "cloud" | "local", scopeId: text(data, "scopeId"), runtimeId, ...(text(data, "runtimeClass") === "" ? {} : { runtimeClass: text(data, "runtimeClass") }), ...(text(data, "deviceId") === "" ? {} : { deviceId: text(data, "deviceId") }) }; const result = await api().runtimeOperation(runtimeId, operation, target, Number(text(data, "expectedRevision")), requestId(`runtime-${operation}`)); state.notice = `${result.runtimeId} 已进入 ${result.state}`; render(root); } catch (error) { fail(root, error); } }
async function traceRun(event: SubmitEvent, root: HTMLElement): Promise<void> { event.preventDefault(); const output = root.querySelector<HTMLElement>("#trace-result"); try { const trace = await api().trace(text(new FormData(event.currentTarget as HTMLFormElement), "runId")); if (output !== null) output.innerHTML = `<div class="trace-summary"><strong>${escape(trace.runId)}</strong>${trace.target === undefined ? "" : `<span>${escape(trace.target.plane)} · ${escape(trace.target.scopeId)} · ${escape(trace.target.runtimeId)}</span>`}</div><div class="trace-columns"><div><p>已记录事实</p>${trace.facts.length === 0 ? "<em>无</em>" : trace.facts.map((fact) => `<div class="fact"><b>${escape(fact.source)}</b><span>${escape(fact.kind)}</span><code>${escape(fact.ref)}</code></div>`).join("")}</div><div><p>缺失边界</p>${trace.missingBoundaries.length === 0 ? "<em>无</em>" : trace.missingBoundaries.map((item) => `<div class="fact missing"><b>${escape(item.source)}</b><span>${escape(item.reason)}</span></div>`).join("")}</div></div>`; } catch (error) { if (output !== null) output.textContent = messageFor(error); } }
function fail(root: HTMLElement, error: unknown): void { state.error = messageFor(error); render(root); }
async function login(event: SubmitEvent, root: HTMLElement): Promise<void> { event.preventDefault(); try { const data = new FormData(event.currentTarget as HTMLFormElement); const username = text(data, "username"); const session = await new AdminApiClient(window.location.origin, window.fetch.bind(window)).login(username, text(data, "password")); state.username = username; state.token = session.accessToken; state.scopeId = text(data, "scopeId"); localStorage.setItem("agentloop.admin.token", state.token); localStorage.setItem("agentloop.admin.username", state.username); localStorage.setItem("agentloop.admin.scope", state.scopeId); state.notice = "登录成功"; await refresh(root); } catch (error) { fail(root, error); } }

function metric(label: string, value: number, hint: string): string { return `<article class="metric"><p>${label}</p><strong>${value}</strong><span>${hint}</span></article>`; }
function quick(title: string, description: string, page: Page): string { return `<button class="quick" data-page="${page}"><strong>${title}</strong><span>${description}</span><b>→</b></button>`; }
function permissionNote(textValue: string): string { return `<article class="panel muted-panel"><p class="panel-kicker">只读边界</p><h3>操作权限受限</h3><p>${escape(textValue)}</p></article>`; }
function emptyRow(columns: number, message: string): string { return `<tr><td colspan="${columns}"><div class="empty">${escape(message)}</div></td></tr>`; }
function statusPill(value: string): string { const tone = value === "active" || value === "loaded" ? "success" : value === "draft" || value === "planned" || value === "invited" ? "neutral" : value === "suspended" || value === "rolled_back" || value === "failed" ? "danger" : "warn"; return `<span class="pill ${tone}">${escape(value)}</span>`; }
function nextReleaseState(value: ReleaseState): ReleaseState | undefined { const next: Partial<Record<ReleaseState, ReleaseState>> = { draft: "validated", validated: "observe", observe: "canary", canary: "active", active: "superseded", superseded: "retired", rolled_back: "retired" }; return next[value]; }
function pageTitle(page: Page): string { return ({ overview: "CONTROL PLANE", releases: "CONFIGURATION", skills: "SKILL OPERATIONS", members: "ACCESS CONTROL", runtime: "RUNTIME OPERATIONS", traces: "RUN TRACE", audit: "AUDIT", settings: "SETTINGS" })[page]; }
function pageHeading(page: Page): string { return ({ overview: "管理概览", releases: "配置发布", skills: "Skill 运营", members: "成员与权限", runtime: "Runtime 运维", traces: "任务追踪", audit: "审计记录", settings: "连接设置" })[page]; }
function labelForKind(kind: ResourceKind): string { const labels: Record<ResourceKind, string> = { model_route: "模型路由", integration: "集成", skill: "Skill", policy: "策略" }; return labels[kind]; }
function roleOptions(): string { return (["platform_admin", "operator", "skill_operator", "auditor", "member"] as const).map((role) => `<option value="${role}">${role}</option>`).join(""); }
function formatTime(value: number): string { return Number.isFinite(value) && value > 0 ? new Intl.DateTimeFormat("zh-CN", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value)) : "—"; }
function text(data: FormData, name: string): string { return String(data.get(name) ?? "").trim(); }
function escape(value: string): string { return value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character]!); }
function messageFor(error: unknown): string { return error instanceof AdminApiError ? `${error.status}${error.code === undefined ? "" : ` · ${error.code}`}` : error instanceof Error ? error.message : "未知错误"; }
async function contentHash(kind: ResourceKind, schemaVersion: string, payload: Record<string, unknown>): Promise<string> { const bytes = new TextEncoder().encode(canonicalJson({ kind, schemaVersion, payload })); const digest = await crypto.subtle.digest("SHA-256", bytes); return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, "0")).join(""); }
function canonicalJson(value: unknown): string { if (value === null || typeof value !== "object") return JSON.stringify(value); if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`; const record = value as Record<string, unknown>; return `{${Object.keys(record).sort().map((key) => `${JSON.stringify(key)}:${canonicalJson(record[key])}`).join(",")}}`; }
