import type { AdminMember, AdminMemberRole, AdminUser, AdminUserStatus, ResourceRelease, RuntimeInventoryEntry, RuntimeTarget } from "../../../control-plane/contracts/index.ts";
import type { RouterRunDetail, RouterRunPage } from "../../../src/shared/contracts.ts";
import { AdminApiClient, AdminApiError, type AdminModelSummary, type AdminProviderSummary, type AdminSession, type AdminSkillDetail, type AdminSkillPage, type RegisterModelInput, type BusinessUserSummary } from "../shared/api/admin-api-client.ts";
import { renderAdminLoginPage } from "./login-page.ts";
import { bindAdminShell } from "./interaction-bindings.ts";
import { optionalProjection } from "./optional-projection.ts";
import { hasPermission, visibleNavigation, type Page } from "./navigation.ts";
import { buildSkillFileTree, type SkillFileTreeNode } from "./skill-file-tree.ts";
import { renderSidebarNavigation } from "./sidebar.ts";
import { createInitialUiState, type AuditRow, type UiState } from "./ui-state.ts";

const state = createInitialUiState();
export function bootAdminWeb(root: HTMLElement): void { void refresh(root); }
function api(): AdminApiClient { return new AdminApiClient(window.location.origin, window.fetch.bind(window), state.token === "" ? undefined : `Bearer ${state.token}`); }
function can(permission: Parameters<typeof hasPermission>[1]): boolean { return hasPermission(state.session, permission); }
function requestId(prefix: string): string { return `${prefix}:${crypto.randomUUID()}`; }

async function refresh(root: HTMLElement): Promise<void> {
  state.error = undefined;
  state.degradedErrors = [];
  try {
    await api().health();
    state.healthy = true;
    if (state.token !== "") {
      state.session = await api().session();
      const failures: string[] = [];
      [state.resources, state.releases, state.models, state.providers, state.skills, state.members, state.users, state.audit, state.runs, state.runtimes] = await Promise.all([
        optionalProjection("resources", () => can("release.read") ? api().resources() : Promise.resolve([]), state.resources, failures, messageFor), optionalProjection("releases", () => can("release.read") ? api().releases() : Promise.resolve([]), state.releases, failures, messageFor), optionalProjection("models", () => can("release.read") ? api().models() : Promise.resolve([]), state.models, failures, messageFor), optionalProjection("providers", () => can("release.read") ? api().providers() : Promise.resolve([]), state.providers, failures, messageFor), optionalProjection("Skills", () => can("skill.read") ? api().skills(state.skillPage, state.skills.pageSize) : Promise.resolve(state.skills), state.skills, failures, messageFor), Promise.resolve([]), optionalProjection("Admin users", () => can("user.read") ? api().users() : Promise.resolve([]), state.users, failures, messageFor), optionalProjection("audit", () => can("audit.read") ? api().auditEvents(50) : Promise.resolve(state.audit), state.audit, failures, messageFor), optionalProjection("Runs", () => can("trace.read") ? api().runs(state.runPage, state.runs.pageSize) : Promise.resolve(state.runs), state.runs, failures, messageFor), optionalProjection("Runtime instances", () => can("runtime.operate") ? api().runtimes(state.runtimePage, state.runtimes.pageSize) : Promise.resolve(state.runtimes), state.runtimes, failures, messageFor),
      ]);
      state.businessUsers = await optionalProjection("Business users", () => can("user.read") ? api().businessUsers() : Promise.resolve(state.businessUsers), state.businessUsers, failures, messageFor);
      state.degradedErrors = failures;
    } else state.session = undefined;
  } catch (error) { state.healthy = false; state.session = undefined; state.error = messageFor(error); }
  render(root);
}

function render(root: HTMLElement): void {
  if (state.session === undefined) {
    root.innerHTML = renderAdminLoginPage({ username: state.username, error: state.error });
    bind(root);
    return;
  }
  const available = visibleNavigation(state.session);
  if (!available.some((item) => item.id === state.page)) state.page = "overview";
  const degraded = state.degradedErrors.length > 0 && (state.page === "traces" || state.page === "business-users" || state.page === "runtime") ? `<div class="degraded-notice" role="status"><strong>Router 数据暂不可用</strong><span>${escape(state.degradedErrors.join("；"))}</span></div>` : "";
  root.innerHTML = `<div class="admin-shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">A</span><span>AgentLoop</span></div><p class="workspace-label">管理控制面</p><nav class="nav" aria-label="管理模块">${renderSidebarNavigation(available, state.page)}</nav><div class="sidebar-footer"><span class="status-dot ${state.healthy ? "ok" : "off"}"></span>${state.healthy ? "Admin API 已连接" : "等待 Admin API 连接"}</div></aside><section class="workspace"><header class="topbar"><div><p class="eyebrow">${pageTitle(state.page)}</p><h1>${pageHeading(state.page)}</h1></div></header><main class="content content-${state.page}">${degraded}${state.error === undefined ? pageContent() : connectionError()}</main></section></div>${state.notice === undefined ? "" : `<div class="toast">${escape(state.notice)}</div>`}`;
  bind(root);
}
function pageContent(): string { switch (state.page) { case "overview": return overviewPage(); case "models": return modelsPage(); case "skills": return skillsPage(); case "admin-users": return membersPage(); case "business-users": return businessUsersPage(); case "runtime": return runtimePage(); case "traces": return runTrackingPage(); case "audit": return auditPage(); } }
function overviewPage(): string { const active = state.releases.filter((release) => release.state === "active").length; const skills = state.releases.filter((release) => release.kind === "skill").length; return `<section class="metric-grid">${metric("已发布资源", state.resources.length, "含版本与并发修订")}${metric("生效 Release", active, "状态为 active")}${metric("Skill Release", skills, "受独立 Skill 权限约束")}${metric("活跃管理用户", state.users.filter((user) => user.status === "active").length, "Admin API 登录用户")}</section><section class="two-column"><article class="panel"><div class="panel-title"><div><p>最近配置变更</p><span>来自不可变审计事件</span></div><button class="text-button" data-page="audit">查看全部</button></div>${auditRows(state.audit.slice(0, 5))}</article><article class="panel"><div class="panel-title"><div><p>运维工作台</p><span>按权限开放入口</span></div></div><div class="quick-actions">${can("skill.write") ? quick("Skill 运营", "查看 Skill 目录", "skills") : ""}${can("runtime.operate") ? quick("Runtime 运维", "执行 drain 或 recover", "runtime") : ""}${can("trace.read") ? quick("任务追踪", "查询 Run 的跨边界事实", "traces") : ""}</div></article></section>`; }

function modelsPage(): string {
  const editing = state.modelEditingKey === undefined ? undefined : state.models.find((model) => model.key === state.modelEditingKey);
  const providers = state.providers.length === 0 ? `<div class="empty">暂无登记 Provider，请先新增 Provider，再在 Provider 下增加模型。</div>` : state.providers.map(providerSection).join("");
  return `<section class="page-grid models-page"><article class="panel wide"><div class="panel-title"><div><p>Provider / 模型目录</p><span>连接配置按 Provider 维护；每个 Provider 下可登记多个模型。保存后写入 Router，Runtime 会在下一次任务准入时读取该版本。</span></div>${can("release.write") ? `<div class="button-row"><button class="secondary" data-action="new-provider">新增 Provider</button><button class="primary" data-action="new-model" ${state.providers.length === 0 ? "disabled" : ""}>新增模型</button></div>` : ""}</div>${providers}</article>${can("release.write") && state.modelModal ? modelForm(editing) : ""}${!can("release.write") ? permissionNote("当前角色没有 release.write，无法新增或修改模型。") : ""}${state.providerModal ? providerForm() : ""}</section>`;
}

function providerForm(): string {
  const editing = state.providerEditingKey === undefined ? undefined : state.providers.find((provider) => provider.key === state.providerEditingKey);
  const isEditing = editing !== undefined;
  return `<div class="dialog-backdrop"><article class="dialog"><button class="dialog-close" data-action="cancel-provider" aria-label="关闭">×</button><p class="eyebrow">PROVIDER SETUP</p><h2>${isEditing ? "编辑 Provider" : "新增 Provider"}</h2><p>Provider 统一维护 Base URL、协议和 API Key；下方模型会继承这些连接配置。API Key 直接保存到 Provider 配置，不使用环境变量。</p><form id="provider-form" class="form-grid"><label>Provider Key<input name="providerKey" value="${escape(editing?.key ?? "")}" ${isEditing ? "readonly" : ""} required placeholder="例如 openai"></label><label>协议<select name="protocol"><option value="chat-completions" ${editing?.protocol !== "responses" ? "selected" : ""}>chat-completions</option><option value="responses" ${editing?.protocol === "responses" ? "selected" : ""}>responses</option></select></label><label class="span-2">Base URL<input name="baseUrl" type="url" value="${escape(editing?.baseUrl ?? "")}" required placeholder="https://api.example.com/v1"></label><label class="span-2">API Key<input name="apiKey" type="password" ${isEditing ? "" : "required"} placeholder="${isEditing ? "留空表示保持现有 Key，填写则覆盖" : "直接填入 Provider API Key"}"></label><label class="checkbox-label span-2"><input name="defaultProvider" type="checkbox" ${editing?.defaultProvider ? "checked" : ""}>设为默认 Provider</label><div class="button-row span-2"><button class="primary" type="submit">${isEditing ? "保存 Provider" : "新增 Provider"}</button><button class="secondary" type="button" data-action="cancel-provider">取消</button></div></form></article></div>`;
}

function providerSection(provider: AdminProviderSummary): string {
  return `<section class="provider-card"><div class="provider-card-head"><div><p class="panel-kicker">PROVIDER</p><h3>${escape(provider.key)} ${provider.defaultProvider ? `<span class="tag purple">默认 Provider</span>` : ""}</h3><small>${escape(provider.baseUrl)} · ${escape(provider.protocol)} · Key ${provider.apiKeyConfigured ? "已配置" : "未配置"}</small></div><div class="button-row"><span class="tag">${provider.models.length} 个模型</span>${can("release.write") ? `${provider.defaultProvider ? "" : `<button class="text-button" data-provider-default="${escape(provider.key)}">设为默认</button>`}<button class="secondary" data-provider-edit="${escape(provider.key)}">编辑 Provider</button><button class="secondary" data-provider-add-model="${escape(provider.key)}">新增模型</button>` : ""}</div></div><div class="table-wrap"><table><thead><tr><th>模型</th><th>上游模型</th><th>状态</th><th>默认</th><th>参数</th><th></th></tr></thead><tbody>${provider.models.length === 0 ? emptyRow(6, "该 Provider 暂无模型") : provider.models.map(modelRow).join("")}</tbody></table></div></section>`;
}

function modelRow(model: AdminModelSummary): string {
  const parameterCount = Object.keys(model.parameters).length + (model.contextWindowTokens === undefined ? 0 : 1) + (model.maxOutputTokens === undefined ? 0 : 1);
  return `<tr><td><strong>${escape(model.displayName)}</strong><small>${escape(model.key)}</small></td><td>${escape(model.providerModel)}</td><td>${statusPill(model.releaseState)}</td><td>${model.defaultModel ? "是" : "否"}</td><td><span class="tag">${parameterCount} 项</span>${parameterCount === 0 ? "" : `<small><code>${escape(JSON.stringify(model.parameters))}</code></small>`}</td><td class="actions">${can("release.write") ? `<button class="text-button" data-model-edit="${escape(model.key)}">编辑</button><button class="text-button danger-link" data-model-delete="${escape(model.key)}">删除</button>` : ""}</td></tr>`;
}

function modelForm(editing?: AdminModelSummary): string {
  const selectedProvider = state.modelProviderKey ?? editing?.providerKey ?? state.providers[0]?.key ?? "";
  const params = editing === undefined ? {} : { ...editing.parameters, ...(editing.contextWindowTokens === undefined ? {} : { contextWindowTokens: editing.contextWindowTokens }), ...(editing.maxOutputTokens === undefined ? {} : { maxOutputTokens: editing.maxOutputTokens }) };
  const parameterRows = Object.entries(params).map(([key, value]) => modelParameterRow(key, value)).join("");
  return `<div class="dialog-backdrop"><article class="dialog model-dialog"><button class="dialog-close" data-action="cancel-model" aria-label="关闭">×</button><p class="eyebrow">MODEL SETUP</p><h2>${editing === undefined ? "新增模型" : "编辑模型"}</h2><p>模型只挂在已有 Provider 下；Provider 的 Base URL、协议和 API Key 由 Provider 统一维护。</p><form id="model-form" class="form-grid"><label>所属 Provider<select name="providerKey" required>${state.providers.map((provider) => `<option value="${escape(provider.key)}" ${provider.key === selectedProvider ? "selected" : ""}>${escape(provider.key)} · ${escape(provider.baseUrl)}</option>`).join("")}</select></label><label>模型 Key<input name="modelKey" value="${escape(editing?.key ?? "")}" ${editing === undefined ? "" : "readonly"} required placeholder="例如 gpt-5.6-terra"></label><label>显示名称<input name="displayName" value="${escape(editing?.displayName ?? "")}" required placeholder="例如 GPT-5.6 Terra"></label><label>上游模型名<input name="providerModel" value="${escape(editing?.providerModel ?? "")}" required placeholder="例如 gpt-5.6-terra"></label><label class="checkbox-label span-2"><input name="defaultModel" type="checkbox" ${editing?.defaultModel ? "checked" : ""}>设为默认模型</label><div class="model-parameters span-2"><div class="parameter-header"><strong>模型差异参数（key-value）</strong><button class="ghost" type="button" data-action="add-model-parameter">添加参数</button></div><div id="model-parameters">${parameterRows || modelParameterRow()}</div><p class="form-help">值优先按 JSON 解析；字符串请直接输入，布尔值、数字、数组和对象可直接填写 JSON。</p></div><div class="button-row span-2"><button class="primary" type="submit">${editing === undefined ? "登记模型" : "保存模型"}</button><button class="secondary" type="button" data-action="cancel-model">取消</button></div></form></article></div>`;
}

function modelParameterRow(key = "", value: unknown = ""): string { const encoded = typeof value === "string" ? value : JSON.stringify(value); return `<div class="model-parameter-row"><input name="parameterKey" value="${escape(key)}" placeholder="参数名"><input name="parameterValue" value="${escape(encoded ?? "")}" placeholder='字符串或 JSON，例如 {"thinking":false}'><button class="text-button" type="button" data-action="remove-model-parameter" aria-label="删除参数">×</button></div>`; }

function skillsPage(): string {
  const page = state.skills;
  return `<section class="skill-layout"><article class="panel skill-list-panel"><div class="panel-title"><div><p>custom-skills</p><span>只读展示配置目录中的 Skill；点击名称查看 SKILL.md、AgentLoop 元数据与文件结构。</span></div><span class="count">${page.total}</span></div><div class="skill-list">${page.items.length === 0 ? `<div class="empty">当前 custom-skills 没有可展示的 Skill</div>` : page.items.map(skillListRow).join("")}</div><div class="pagination"><button class="ghost" data-action="skill-page-prev" ${page.page <= 1 ? "disabled" : ""}>上一页</button><span>第 ${page.page} / ${page.pageCount} 页 · 共 ${page.total} 个</span><button class="ghost" data-action="skill-page-next" ${page.page >= page.pageCount ? "disabled" : ""}>下一页</button></div></article><article class="panel skill-detail-panel">${state.skillDetail === undefined ? `<div class="skill-empty-detail"><p class="panel-kicker">SKILL INSPECTOR</p><h3>选择一个 Skill</h3><p>左侧列表按分页加载 custom-skills。详情只返回包内相对路径，不暴露服务器目录。</p></div>` : skillDetailView(state.skillDetail)}</article></section>`;
}

function skillListRow(skill: AdminSkillPage["items"][number]): string {
  const selected = state.skillDetail?.name === skill.name ? " selected" : "";
  return `<button class="skill-list-row${selected}" data-skill-name="${escape(skill.name)}"><span class="skill-row-main"><strong>${escape(skill.name)}</strong><small>${escape(skill.description)}</small></span><span class="skill-row-meta"><b>${escape(skill.version ?? "未声明版本")}</b><small>${skill.fileCount} 个文件</small></span></button>`;
}

function skillDetailView(skill: AdminSkillDetail): string {
  return `<div class="skill-detail-head"><div><p class="panel-kicker">CUSTOM SKILL</p><h2>${escape(skill.name)}</h2><p>${escape(skill.description)}</p></div><span class="tag purple">v${escape(skill.version ?? "未声明")}</span></div><div class="skill-facts"><span><b>Package Hash</b><code>${escape(skill.packageHash)}</code></span><span><b>文件</b>${skill.fileCount}</span><span><b>大小</b>${formatBytes(skill.totalBytes)}</span></div><section class="skill-section"><div class="skill-section-title"><h3>AgentLoop 元数据</h3><span>专项字段</span></div>${agentLoopMetadata(skill.agentLoop)}</section><section class="skill-section"><div class="skill-section-title"><h3>SKILL.md 关键内容</h3><span>敏感值已脱敏</span></div><pre class="skill-markdown">${escape(skill.skillMd)}</pre></section><section class="skill-section"><div class="skill-section-title"><h3>文件结构</h3><span>scripts / references / assets 等</span></div><div class="skill-tree">${skillFileTree(skill.files)}</div></section></div>`;
}

function agentLoopMetadata(metadata: AdminSkillDetail["agentLoop"]): string {
  if (metadata === undefined) return `<p class="muted-text">未声明 agentloop 元数据。</p>`;
  const fields: Array<[string, readonly string[] | undefined]> = [["roles", metadata.roles], ["artifactKinds", metadata.artifactKinds], ["sourceKinds", metadata.sourceKinds], ["qaKinds", metadata.qaKinds], ["executionProfiles", metadata.executionProfiles], ["semanticTags", metadata.semanticTags], ["producesEvidenceKinds", metadata.producesEvidenceKinds], ["requiredSkillNames", metadata.requiredSkillNames]];
  return `<div class="metadata-grid">${fields.filter(([, values]) => values !== undefined && values.length > 0).map(([label, values]) => `<div><b>${escape(label)}</b><span>${values!.map((value) => `<em>${escape(value)}</em>`).join("")}</span></div>`).join("")}${metadata.intentExamples === undefined || metadata.intentExamples.length === 0 ? "" : `<div class="metadata-wide"><b>intentExamples</b><span>${metadata.intentExamples.map((value) => `<em>${escape(value)}</em>`).join("")}</span></div>`}</div>`;
}

function skillFileTree(files: readonly string[]): string {
  return `<ul class="skill-tree-branch">${buildSkillFileTree(files).map(skillFileTreeNode).join("")}</ul>`;
}

function skillFileTreeNode(node: SkillFileTreeNode): string {
  if (node.kind === "file") return `<li class="skill-tree-file"><span aria-hidden="true">·</span><code title="${escape(node.path)}">${escape(node.name)}</code></li>`;
  return `<li class="skill-tree-directory"><details open><summary><strong>${escape(node.name)}</strong><small>${node.fileCount} 个文件</small></summary><ul class="skill-tree-branch">${node.children.map(skillFileTreeNode).join("")}</ul></details></li>`;
}


function membersPage(): string {
  const page = adminUserPage();
  return `<section class="members-page"><article class="panel wide"><div class="panel-title"><div><p>管理端用户</p><span>这里管理 Admin API 自己的登录用户、角色和状态，不管理 Multi Runtime 的使用用户。</span></div><div class="panel-actions"><span class="count">${state.users.length}</span>${can("user.write") ? `<button class="primary" data-action="new-user">新增用户</button>` : ""}</div></div><div class="table-wrap"><table><thead><tr><th>用户</th><th>角色</th><th>Scope</th><th>状态</th><th>更新时间</th><th></th></tr></thead><tbody>${state.users.length === 0 ? emptyRow(6, "暂无管理端用户") : page.items.map(adminUserRow).join("")}</tbody></table></div><div class="pagination admin-user-pagination"><button class="ghost" data-action="admin-user-page-prev" ${page.page <= 1 ? "disabled" : ""}>上一页</button><span>第 ${page.page} / ${page.pageCount} 页 · 共 ${state.users.length} 个</span><button class="ghost" data-action="admin-user-page-next" ${page.page >= page.pageCount ? "disabled" : ""}>下一页</button></div></article>${can("user.write") && state.userModal ? adminUserForm() : ""}${!can("user.write") ? permissionNote("当前角色没有 user.write，无法管理 Admin 用户。") : ""}</section>`;
}

function adminUserPage(): { readonly items: readonly AdminUser[]; readonly page: number; readonly pageCount: number } {
  const pageCount = Math.max(1, Math.ceil(state.users.length / state.userPageSize));
  const page = Math.min(Math.max(1, state.userPage), pageCount);
  const start = (page - 1) * state.userPageSize;
  return { items: state.users.slice(start, start + state.userPageSize), page, pageCount };
}
function businessUsersPage(): string {
  const page = state.businessUsers;
  return `<section class="members-page"><article class="panel wide"><div class="panel-title"><div><p>AgentLoop 业务用户</p><span>用户资料、状态和活动时间均来自 Router；Token 消耗账本尚未接入，不做估算。</span></div><span class="count">${page.total}</span></div><div class="table-wrap"><table><thead><tr><th>邮箱</th><th>Tenant</th><th>状态</th><th>创建时间</th><th>最新活动</th><th>Token 消耗</th><th></th></tr></thead><tbody>${page.items.length === 0 ? emptyRow(7, "暂无业务用户") : page.items.map(businessUserRow).join("")}</tbody></table></div><div class="pagination"><button class="ghost" data-action="business-user-prev" ${page.page <= 1 ? "disabled" : ""}>上一页</button><span>第 ${page.page} / ${page.pageCount} 页 · 共 ${page.total} 个</span><button class="ghost" data-action="business-user-next" ${page.page >= page.pageCount ? "disabled" : ""}>下一页</button></div></article>${state.businessUserPasswordId === undefined ? "" : businessPasswordForm()}</section>`;
}
function businessUserRow(user: BusinessUserSummary): string { return `<tr><td><strong>${escape(user.email)}</strong><small>${escape(user.id)}</small></td><td><code>${escape(user.tenantId)}</code></td><td>${statusPill(user.status)}</td><td>${formatTime(user.createdAt)}</td><td>${user.lastActiveAt === undefined ? "暂无活动" : formatTime(user.lastActiveAt)}</td><td><span class="muted-text">暂无消费数据</span></td><td class="actions">${can("user.write") ? `${user.status === "active" ? `<button class="text-button danger-link" data-business-suspend="${escape(user.id)}">停用</button>` : ""}<button class="text-button" data-business-password="${escape(user.id)}">重置密码</button>` : ""}</td></tr>`; }
function businessPasswordForm(): string { return `<div class="dialog-backdrop"><article class="dialog"><button class="dialog-close" data-action="cancel-business-password" aria-label="关闭">×</button><p class="eyebrow">BUSINESS USER</p><h2>重置密码</h2><p>新密码只提交给 Router，Router 不返回密码或密码哈希。</p><form id="business-password-form" class="form-grid"><label class="span-2">新密码<input name="password" type="password" minlength="12" required></label><div class="button-row span-2"><button class="primary" type="submit">确认重置</button><button class="secondary" type="button" data-action="cancel-business-password">取消</button></div></form></article></div>`; }
function adminUserRow(user: AdminUser): string { const next: AdminUserStatus | undefined = user.status === "active" ? "suspended" : user.status === "suspended" ? "active" : undefined; return `<tr><td><strong>${escape(user.displayName)}</strong><small>${escape(user.username)} · ${escape(user.userId)}</small></td><td><span class="tag purple">${escape(user.role)}</span></td><td>${escape(user.scopeId ?? "平台")}</td><td>${statusPill(user.status)}<small>rev ${user.revision}</small></td><td>${formatTime(user.updatedAt)}</td><td class="actions"><button class="text-button" data-user-edit="${escape(user.userId)}">编辑</button>${next === undefined ? "" : `<button class="text-button" data-user-transition="${escape(user.userId)}" data-user-status="${next}" data-user-revision="${user.revision}">${next === "active" ? "启用" : "停用"}</button>`}</td></tr>`; }
function adminUserForm(): string { const editing = state.userEditingId === undefined ? undefined : state.users.find((user) => user.userId === state.userEditingId); return `<div class="dialog-backdrop"><article class="dialog admin-user-dialog"><button class="dialog-close" data-action="cancel-user-edit" aria-label="关闭">×</button><p class="eyebrow">ADMIN USER</p><h2>${editing === undefined ? "新增管理端用户" : "编辑管理端用户"}</h2><p>密码只提交给 Admin API，数据库仅保存 scrypt hash。</p><form id="admin-user-form" class="form-grid"><label>用户名<input name="username" value="${escape(editing?.username ?? "")}" ${editing === undefined ? "" : "readonly"} required placeholder="例如 ops@example.com"></label><label>显示名称<input name="displayName" value="${escape(editing?.displayName ?? "")}" required></label><label>Scope ID<input name="scopeId" value="${escape(editing?.scopeId ?? "")}" placeholder="留空表示平台范围"></label><label>角色<select name="role">${roleOptions(editing?.role)}</select></label><label class="span-2">${editing === undefined ? "初始密码" : "重置密码（留空不修改）"}<input name="password" type="password" ${editing === undefined ? "required" : ""} minlength="12" placeholder="至少 12 个字符"></label><div class="button-row span-2"><button class="primary" type="submit">${editing === undefined ? "创建用户" : "保存用户"}</button><button class="secondary" type="button" data-action="cancel-user-edit">取消</button></div></form></article></div>`; }
function memberForm(): string { return `<article class="panel form-panel"><div class="panel-title"><div><p>添加成员</p><span>角色是管理端权限的来源，不绑定 Router 用户会话。</span></div></div><form id="member-form" class="form-grid"><label>Subject<input name="subject" required placeholder="例如 ops@example.com"></label><label>显示名称<input name="displayName" required placeholder="例如 运维同学"></label><label>Scope ID<input name="scopeId" value="${escape(state.scopeId)}" required></label><label>角色<select name="role">${roleOptions()}</select></label><button class="primary span-2" type="submit">创建成员</button></form></article>`; }
function runtimePage(): string {
  const page = state.runtimes;
  return `<section class="page-grid runtime-page"><article class="panel wide runtime-list-panel"><div class="panel-title"><div><p>当前 Runtime 实例</p><span>按启动时间倒序；只读数据来自 Router 已登记的 Cloud Host 与已连接的 Local Runtime。</span></div><span class="count">${page.total}</span></div><div class="table-wrap"><table><thead><tr><th>实例</th><th>Plane / Profile</th><th>状态</th><th>容量</th><th>启动时间</th><th>操作</th></tr></thead><tbody>${page.items.length === 0 ? emptyRow(6, "Router 当前没有登记 Runtime 实例") : page.items.map(runtimeRow).join("")}</tbody></table></div><div class="pagination"><button class="ghost" data-action="runtime-page-prev" ${page.page <= 1 ? "disabled" : ""}>上一页</button><span>第 ${page.page} / ${page.pageCount} 页 · 共 ${page.total} 个</span><button class="ghost" data-action="runtime-page-next" ${page.page >= page.pageCount ? "disabled" : ""}>下一页</button></div></article></section>`;
}

function runtimeRow(runtime: RuntimeInventoryEntry): string {
  const name = runtime.displayName ?? runtime.id;
  const capacity = `${runtime.activeRunCount} 活跃 · ${runtime.queuedRunCount} 排队 / ${runtime.maxConcurrentRuns}`;
  const heartbeat = runtime.lastHeartbeatAt === undefined ? "尚未收到心跳" : formatTime(runtime.lastHeartbeatAt);
  const actions = runtime.plane === "local" ? `<span class="muted-text">本地 Runtime 不支持运维操作</span>` : `<button class="text-button danger-link" data-runtime-operation="drain" data-runtime-id="${escape(runtime.id)}">Drain</button><button class="text-button" data-runtime-operation="recover" data-runtime-id="${escape(runtime.id)}">Recover</button><button class="text-button" data-runtime-operation="restart" data-runtime-id="${escape(runtime.id)}">Restart</button>`;
  return `<tr><td><strong>${escape(name)}</strong><small>${escape(runtime.id)}${runtime.deviceId === undefined ? "" : ` · device ${escape(runtime.deviceId)}`}${runtime.scopeId === undefined ? "" : ` · scope ${escape(runtime.scopeId)}`}</small></td><td>${escape(runtime.plane)}<small>${escape(runtime.profile)}${runtime.catalogVersion === undefined ? "" : ` · catalog ${escape(runtime.catalogVersion)}`}</small></td><td>${runtimeStatusPill(runtime.status)}</td><td>${escape(capacity)}<small>${runtime.capabilities.length === 0 ? "未声明 capability" : escape(runtime.capabilities.join(" · "))}</small></td><td>${escape(formatTime(runtime.startedAt))}<small>${escape(heartbeat)}</small></td><td class="actions">${actions}</td></tr>`;
}
function tracesPage(): string {
  const page = state.runs;
  return `<section class="run-operations"><article class="panel run-list-panel"><div class="panel-title"><div><p>当前 Run 列表</p><span>按更新时间分页；状态与结果只来自 Router/Runtime 的持久化投影。</span></div><span class="count">${page.total}</span></div><div class="table-wrap"><table><thead><tr><th>用户指令</th><th>状态</th><th>Runtime</th><th>计划</th><th>结果</th><th>更新时间</th></tr></thead><tbody>${page.items.length === 0 ? emptyRow(6, "暂无 Run") : page.items.map(runRow).join("")}</tbody></table></div><div class="pagination"><button class="ghost" data-action="run-page-prev" ${page.page <= 1 ? "disabled" : ""}>上一页</button><span>第 ${page.page} / ${page.pageCount} 页 · 共 ${page.total} 个</span><button class="ghost" data-action="run-page-next" ${page.page >= page.pageCount ? "disabled" : ""}>下一页</button></div></article><article class="panel run-detail-panel">${state.runDetail === undefined ? `<div class="skill-empty-detail"><p class="panel-kicker">RUN OPERATIONS</p><h3>选择一个 Run</h3><p>点击列表行查看完整计划、canonical Outcome、Runtime 与产物。</p></div>` : runDetailView(state.runDetail)}</article></section>`;
}

/** Full-width Run table; the detailed Router/Runtime projection is a modal. */
function runTrackingPage(): string {
  const page = state.runs;
  return `<section class="run-operations run-tracking-page"><article class="panel run-list-panel"><div class="panel-title"><div><p>当前 Run 列表</p><span>按更新时间分页；状态与结果只来自 Router/Runtime 的持久化投影。用户产物仅保留数量，不展示隐私元数据。</span></div><span class="count">${page.total}</span></div><div class="table-wrap"><table><thead><tr><th>用户指令</th><th>状态</th><th>Runtime</th><th>计划</th><th>结果</th><th>更新时间</th></tr></thead><tbody>${page.items.length === 0 ? emptyRow(6, "暂无 Run") : page.items.map(runRow).join("")}</tbody></table></div><div class="pagination"><button class="ghost" data-action="run-page-prev" ${page.page <= 1 ? "disabled" : ""}>上一页</button><span>第 ${page.page} / ${page.pageCount} 页 · 共 ${page.total} 个</span><button class="ghost" data-action="run-page-next" ${page.page >= page.pageCount ? "disabled" : ""}>下一页</button></div></article>${state.runDetail === undefined ? "" : `<div class="dialog-backdrop"><article class="dialog run-detail-dialog"><button class="dialog-close" data-action="close-run-detail" aria-label="关闭">×</button>${adminRunDetailView(state.runDetail)}</article></div>`}</section>`;
}

function adminRunDetailView(run: RouterRunDetail): string {
  // Keep the metadata section (name, MIME type, size, count), but never add
  // artifact bytes, previews, or download links to the Admin surface.
  return runDetailView(run);
}

function runRow(run: RouterRunPage["items"][number]): string {
  const selected = state.runDetail?.id === run.id ? " selected" : "";
  const input = run.input === undefined ? "（严格本地输入未在 Router 保存）" : run.input;
  const result = run.status === "failed" ? (run.errorMessage ?? run.errorCode ?? "失败") : (run.output ?? "—");
  return `<tr class="run-row${selected}" data-run-id="${escape(run.id)}"><td><strong>${escape(input.slice(0, 80))}</strong><small>${escape(run.id)}</small></td><td>${statusPill(run.status)}</td><td>${escape(run.runtimeName ?? run.runtimeId ?? "—")}<small>${escape(run.modelKey ?? "")}</small></td><td>${run.planStepCount === undefined ? "—" : `${run.planStepCount} 步`}<small>${escape(run.planState ?? "")}</small></td><td><span class="run-result">${escape(result.slice(0, 80))}</span><small>${run.artifactCount === undefined ? "" : `${run.artifactCount} 个产物`}</small></td><td>${formatTime(run.updatedAt)}</td></tr>`;
}

function runDetailView(run: RouterRunDetail): string {
  const plan = run.plan;
  const outcome = run.outcome;
  return `<div class="run-detail-head"><div><p class="panel-kicker">RUN OPERATIONS</p><h2>${escape(run.id)}</h2><p>${escape(run.input ?? "严格本地输入未在 Router 保存")}</p></div>${statusPill(run.status)}</div><div class="run-facts"><span><b>Runtime</b>${escape(run.runtimeName ?? run.runtimeId ?? "—")}</span><span><b>模型</b>${escape(run.modelKey ?? "—")}</span><span><b>创建</b>${formatTime(run.createdAt)}</span><span><b>更新</b>${formatTime(run.updatedAt)}</span></div><section class="skill-section"><div class="skill-section-title"><h3>Plan / 计划步骤</h3><span>${plan === undefined ? "Runtime 边界不可用" : `${plan.steps.length} 步 · ${escape(plan.status)}`}</span></div>${plan === undefined ? `<p class="muted-text">未能读取 Host canonical Plan。</p>` : `<p>${escape(plan.goal)}</p><div class="run-steps">${plan.steps.map((step, index) => `<div class="run-step"><b>${index + 1}. ${escape(step.objective)}</b><span>${statusPill(step.status)}</span>${step.output === undefined ? "" : `<p>${escape(step.output)}</p>`}${step.error === undefined ? "" : `<p class="danger-text">${escape(step.error)}</p>`}</div>`).join("")}</div>`}</section><section class="skill-section"><div class="skill-section-title"><h3>Canonical Outcome</h3><span>${outcome === undefined ? "未读取" : escape(outcome.reasonCode)}</span></div>${outcome === undefined ? `<p class="muted-text">Outcome 不可用；不能据此推断任务成功。</p>` : `<div class="outcome-card ${outcome.status === "completed" ? "success" : "failed"}"><strong>${escape(outcome.status)}</strong><p>${escape(outcome.output ?? run.output ?? run.errorMessage ?? "")}</p><small>提交时间 ${formatTime(outcome.committedAt)}</small></div>`}</section><section class="skill-section"><div class="skill-section-title"><h3>产物</h3><span>${run.artifacts.length} 个</span></div>${run.artifacts.length === 0 ? `<p class="muted-text">暂无已确认产物。</p>` : `<ul class="artifact-list">${run.artifacts.map((artifact) => `<li><strong>${escape(artifact.name)}</strong><small>${escape(artifact.mimeType)} · ${artifact.bytes} bytes</small></li>`).join("")}</ul>`}</section>${run.missingBoundaries.length === 0 ? "" : `<div class="boundary-warning"><b>缺失边界</b><span>${run.missingBoundaries.map((item) => escape(item)).join("、")}</span></div>`}</div>`;
}
function auditPage(): string { return `<section class="panel"><div class="panel-title"><div><p>审计记录</p><span>不可变操作事实，按记录时间倒序。</span></div><span class="count">${state.audit.length}</span></div>${auditRows(state.audit)}</section>`; }
function connectionError(): string { return `<section class="error-wrap"><article class="panel error-panel"><p class="eyebrow">管理端不可用</p><h2>无法建立管理会话</h2><p>${escape(state.error ?? "未知错误")}</p><button class="primary" data-page="overview">返回总览</button></article></section>`; }

function memberRow(member: AdminMember): string { const next = member.status === "active" ? "suspended" : member.status === "suspended" || member.status === "invited" ? "active" : undefined; return `<tr><td><strong>${escape(member.displayName)}</strong><small>${escape(member.subject)}</small></td><td><span class="tag">${escape(member.role)}</span></td><td>${statusPill(member.status)}</td><td>${member.revision}</td><td class="actions">${can("member.write") && next !== undefined ? `<button class="text-button" data-member-transition="${escape(member.memberId)}" data-member-state="${next}" data-member-revision="${member.revision}">${next === "active" ? "启用" : "暂停"}</button>` : ""}</td></tr>`; }
function auditRows(events: readonly AuditRow[]): string { return events.length === 0 ? `<div class="empty">暂无审计记录</div>` : `<div class="activity">${events.map((event) => `<div class="activity-row"><span class="activity-dot"></span><div><strong>${escape(event.action)}</strong><p>${escape(event.actorId)} · ${escape(event.resourceId)}${event.releaseId === undefined ? "" : ` · ${escape(event.releaseId)}`}</p></div><time>${formatTime(event.createdAt)}</time></div>`).join("")}</div>`; }

function bind(root: HTMLElement): void {
  bindAdminShell(root, { state, render, login, saveModel, saveProvider, setDefaultProvider, deleteModel, selectSkill, changeSkillPage, selectRun, changeRunPage, createMember, saveAdminUser, transitionAdminUser, changeAdminUserPage, runtimeRowOperation, changeRuntimePage, traceRun, transitionMember, suspendBusinessUser, resetBusinessPassword });
}

async function createMember(event: SubmitEvent, root: HTMLElement): Promise<void> { event.preventDefault(); try { const data = new FormData(event.currentTarget as HTMLFormElement); const now = Date.now(); await api().createMember({ contractVersion: "control-plane/v1", memberId: `member-${crypto.randomUUID()}`, scopeId: text(data, "scopeId"), subject: text(data, "subject"), displayName: text(data, "displayName"), role: text(data, "role") as AdminMemberRole, status: "active", revision: 1, createdAt: now, updatedAt: now }, 0, requestId("member-create")); state.notice = "成员已创建"; await refresh(root); } catch (error) { fail(root, error); } }
async function saveAdminUser(event: SubmitEvent, root: HTMLElement): Promise<void> { event.preventDefault(); try { const data = new FormData(event.currentTarget as HTMLFormElement); const password = text(data, "password"); const editing = state.userEditingId === undefined ? undefined : state.users.find((user) => user.userId === state.userEditingId); if (editing === undefined) { const now = Date.now(); await api().createUser({ contractVersion: "control-plane/v1", userId: `admin-user-${crypto.randomUUID()}`, username: text(data, "username"), displayName: text(data, "displayName"), ...(text(data, "scopeId") === "" ? {} : { scopeId: text(data, "scopeId") }), role: text(data, "role") as AdminMemberRole, status: "active", revision: 1, createdAt: now, updatedAt: now }, password, requestId("admin-user-create")); } else { await api().updateUser(editing.userId, { displayName: text(data, "displayName"), ...(text(data, "scopeId") === "" ? {} : { scopeId: text(data, "scopeId") }), role: text(data, "role") as AdminMemberRole, expectedRevision: editing.revision }, requestId("admin-user-update")); if (password !== "") await api().resetUserPassword(editing.userId, password, editing.revision + 1, requestId("admin-user-password")); } state.userEditingId = undefined; state.userModal = false; state.notice = "管理端用户已保存"; await refresh(root); } catch (error) { fail(root, error); } }
async function transitionAdminUser(button: HTMLElement, root: HTMLElement): Promise<void> { try { await api().transitionUser(button.dataset.userTransition!, button.dataset.userStatus as AdminUserStatus, Number(button.dataset.userRevision), requestId("admin-user-transition")); state.notice = "管理端用户状态已更新"; await refresh(root); } catch (error) { fail(root, error); } }
function changeAdminUserPage(page: number, root: HTMLElement): void { const pageCount = Math.max(1, Math.ceil(state.users.length / state.userPageSize)); if (page < 1 || page > pageCount) return; state.userPage = page; render(root); }
async function transitionMember(button: HTMLElement, root: HTMLElement): Promise<void> { try { await api().transitionMember(button.dataset.memberTransition!, button.dataset.memberState as "active" | "suspended", Number(button.dataset.memberRevision), requestId("member-transition")); state.notice = "成员状态已更新"; await refresh(root); } catch (error) { fail(root, error); } }
async function suspendBusinessUser(id: string, root: HTMLElement): Promise<void> { try { await api().suspendBusinessUser(id); state.notice = "业务用户已停用，现有会话已撤销"; await refresh(root); } catch (error) { fail(root, error); } }
async function resetBusinessPassword(event: SubmitEvent, root: HTMLElement): Promise<void> { event.preventDefault(); if (state.businessUserPasswordId === undefined) return; try { const password = text(new FormData(event.currentTarget as HTMLFormElement), "password"); await api().resetBusinessUserPassword(state.businessUserPasswordId, password); state.businessUserPasswordId = undefined; state.notice = "业务用户密码已重置"; await refresh(root); } catch (error) { fail(root, error); } }
async function changeRuntimePage(page: number, root: HTMLElement): Promise<void> { if (page < 1 || page > state.runtimes.pageCount) return; state.runtimePage = page; try { state.runtimes = await api().runtimes(page, state.runtimes.pageSize); render(root); } catch (error) { fail(root, error); } }
async function runtimeRowOperation(button: HTMLElement, root: HTMLElement): Promise<void> {
  const runtime = state.runtimes.items.find((item) => item.id === button.dataset.runtimeId);
  const operation = button.dataset.runtimeOperation as "drain" | "recover" | "restart" | undefined;
  if (runtime === undefined || operation === undefined || runtime.plane === "local") return;
  if (!window.confirm(`确认对 Runtime ${runtime.displayName ?? runtime.id} 执行 ${operation}？`)) return;
  try {
    const result = await api().runtimeOperation(runtime.id, operation, { plane: "cloud", scopeId: runtime.scopeId ?? state.scopeId, runtimeId: runtime.id, runtimeClass: runtime.profile }, 0, requestId(`runtime-${operation}`));
    state.notice = `${result.runtimeId} 已进入 ${result.state}`;
    await refresh(root);
  } catch (error) { fail(root, error); }
}
async function traceRun(event: SubmitEvent, root: HTMLElement): Promise<void> { event.preventDefault(); const output = root.querySelector<HTMLElement>("#trace-result"); try { const trace = await api().trace(text(new FormData(event.currentTarget as HTMLFormElement), "runId")); if (output !== null) output.innerHTML = `<div class="trace-summary"><strong>${escape(trace.runId)}</strong>${trace.target === undefined ? "" : `<span>${escape(trace.target.plane)} · ${escape(trace.target.scopeId)} · ${escape(trace.target.runtimeId)}</span>`}</div><div class="trace-columns"><div><p>已记录事实</p>${trace.facts.length === 0 ? "<em>无</em>" : trace.facts.map((fact) => `<div class="fact"><b>${escape(fact.source)}</b><span>${escape(fact.kind)}</span><code>${escape(fact.ref)}</code></div>`).join("")}</div><div><p>缺失边界</p>${trace.missingBoundaries.length === 0 ? "<em>无</em>" : trace.missingBoundaries.map((item) => `<div class="fact missing"><b>${escape(item.source)}</b><span>${escape(item.reason)}</span></div>`).join("")}</div></div>`; } catch (error) { if (output !== null) output.textContent = messageFor(error); } }
async function saveModel(event: SubmitEvent, root: HTMLElement): Promise<void> { event.preventDefault(); try { const form = event.currentTarget as HTMLFormElement; const data = new FormData(form); const model = modelInput(data); const current = state.modelEditingKey === undefined ? undefined : state.models.find((item) => item.key === state.modelEditingKey); const result = current === undefined ? await api().registerModel(model, requestId("model-register")) : await api().updateModel(current.key, model, requestId("model-update")); state.modelEditingKey = undefined; state.modelProviderKey = undefined; state.modelModal = false; state.notice = modelCatalogNotice(result, "模型"); await refresh(root); } catch (error) { fail(root, error); } }
async function saveProvider(event: SubmitEvent, root: HTMLElement): Promise<void> { event.preventDefault(); try { const data = new FormData(event.currentTarget as HTMLFormElement); const apiKey = text(data, "apiKey"); const result = await api().registerProvider({ providerKey: text(data, "providerKey"), baseUrl: text(data, "baseUrl"), ...(apiKey === "" ? {} : { apiKey }), protocol: text(data, "protocol") as "chat-completions" | "responses", defaultProvider: data.get("defaultProvider") === "on" }, requestId("provider-register")); state.providerEditingKey = undefined; state.providerModal = false; state.notice = modelCatalogNotice(result, "Provider"); await refresh(root); } catch (error) { fail(root, error); } }
async function setDefaultProvider(providerKey: string, root: HTMLElement): Promise<void> { try { const result = await api().setDefaultProvider(providerKey, requestId("provider-default")); state.notice = modelCatalogNotice(result, "默认 Provider"); await refresh(root); } catch (error) { fail(root, error); } }
async function deleteModel(modelKey: string, root: HTMLElement): Promise<void> { try { const result = await api().deleteModel(modelKey, requestId("model-delete")); state.notice = modelCatalogNotice(result, "模型"); await refresh(root); } catch (error) { fail(root, error); } }
async function selectSkill(name: string, root: HTMLElement): Promise<void> { try { state.skillDetail = await api().skill(name); state.page = "skills"; render(root); } catch (error) { fail(root, error); } }
async function changeSkillPage(page: number, root: HTMLElement): Promise<void> { if (page < 1 || page > state.skills.pageCount) return; state.skillPage = page; try { state.skills = await api().skills(page, state.skills.pageSize); state.skillDetail = undefined; render(root); } catch (error) { fail(root, error); } }
async function selectRun(id: string, root: HTMLElement): Promise<void> { try { state.runDetail = await api().run(id); state.page = "traces"; render(root); } catch (error) { fail(root, error); } }
async function changeRunPage(page: number, root: HTMLElement): Promise<void> { if (page < 1 || page > state.runs.pageCount) return; state.runPage = page; try { state.runs = await api().runs(page, state.runs.pageSize); state.runDetail = undefined; render(root); } catch (error) { fail(root, error); } }
function modelInput(data: FormData): RegisterModelInput { const parameters: Record<string, unknown> = {}; const seen = new Set<string>(); const keys = data.getAll("parameterKey").map(String); const values = data.getAll("parameterValue").map(String); keys.forEach((key, index) => { const trimmed = key.trim(); if (trimmed === "") return; if (seen.has(trimmed)) throw new Error(`模型参数 ${trimmed} 重复`); seen.add(trimmed); const raw = values[index]?.trim() ?? ""; try { parameters[trimmed] = raw === "" ? "" : JSON.parse(raw); } catch { parameters[trimmed] = raw; } }); const providerKey = text(data, "providerKey"); const provider = state.providers.find((item) => item.key === providerKey); if (provider === undefined) throw new Error("请选择一个已登记的 Provider"); const contextWindowTokens = optionalNumber(data, "contextWindowTokens"); return { modelKey: text(data, "modelKey"), displayName: text(data, "displayName"), providerKey, providerModel: text(data, "providerModel"), baseUrl: provider.baseUrl, protocol: provider.protocol, defaultModel: data.get("defaultModel") === "on", ...(contextWindowTokens === undefined ? {} : { contextWindowTokens }), parameters }; }
function optionalNumber(data: FormData, name: string): number | undefined { const value = text(data, name); return value === "" ? undefined : Number(value); }
function modelCatalogNotice(result: ResourceRelease, label: string): string { return result.state === "active" ? `${label}已写入 Router 模型目录，Runtime 下次任务准入时会读取新配置` : `${label}已生成 Draft Release，请完成发布与目标分配`; }
function fail(root: HTMLElement, error: unknown): void { state.error = messageFor(error); render(root); }
async function login(event: SubmitEvent, root: HTMLElement): Promise<void> { event.preventDefault(); try { const data = new FormData(event.currentTarget as HTMLFormElement); const username = text(data, "username"); const requestedScope = text(data, "scopeId"); const session = await new AdminApiClient(window.location.origin, window.fetch.bind(window)).login(username, text(data, "password")); state.username = username; state.token = session.accessToken; if (requestedScope !== "") state.scopeId = requestedScope; localStorage.setItem("agentloop.admin.token", state.token); localStorage.setItem("agentloop.admin.username", state.username); localStorage.setItem("agentloop.admin.scope", state.scopeId); state.notice = "登录成功"; await refresh(root); } catch (error) { fail(root, error); } }

function metric(label: string, value: number, hint: string): string { return `<article class="metric"><p>${label}</p><strong>${value}</strong><span>${hint}</span></article>`; }
function quick(title: string, description: string, page: Page): string { return `<button class="quick" data-page="${page}"><strong>${title}</strong><span>${description}</span><b>→</b></button>`; }
function permissionNote(textValue: string): string { return `<article class="panel muted-panel"><p class="panel-kicker">只读边界</p><h3>操作权限受限</h3><p>${escape(textValue)}</p></article>`; }
function emptyRow(columns: number, message: string): string { return `<tr><td colspan="${columns}"><div class="empty">${escape(message)}</div></td></tr>`; }
function statusPill(value: string): string { const tone = value === "active" || value === "loaded" ? "success" : value === "draft" || value === "planned" || value === "invited" ? "neutral" : value === "suspended" || value === "rolled_back" || value === "failed" ? "danger" : "warn"; return `<span class="pill ${tone}">${escape(value)}</span>`; }
function runtimeStatusPill(value: RuntimeInventoryEntry["status"]): string { const tone = value === "ready" ? "success" : value === "offline" ? "danger" : "warn"; return `<span class="pill ${tone}">${escape(value)}</span>`; }
function pageTitle(page: Page): string { return ({ overview: "CONTROL PLANE", models: "MODEL CATALOG", skills: "SKILL OPERATIONS", "admin-users": "ADMINISTRATION", "business-users": "BUSINESS OPERATIONS", runtime: "RUNTIME OPERATIONS", traces: "TASK TRACKING", audit: "AUDIT" })[page]; }
function pageHeading(page: Page): string { return ({ overview: "管理概览", models: "模型管理", skills: "Skill 运营", "admin-users": "管理端用户", "business-users": "业务端用户", runtime: "Runtime 运维", traces: "任务跟踪", audit: "审计记录" })[page]; }
function roleOptions(selected?: AdminMemberRole): string { return (["platform_admin", "operator", "skill_operator", "auditor", "member"] as const).map((role) => `<option value="${role}" ${selected === role ? "selected" : ""}>${role}</option>`).join(""); }
function formatTime(value: number): string { return Number.isFinite(value) && value > 0 ? new Intl.DateTimeFormat("zh-CN", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value)) : "—"; }
function formatBytes(value: number): string { if (value < 1_024) return `${value} B`; if (value < 1_024 * 1_024) return `${(value / 1_024).toFixed(1)} KB`; return `${(value / (1_024 * 1_024)).toFixed(1)} MB`; }
function text(data: FormData, name: string): string { return String(data.get(name) ?? "").trim(); }
function escape(value: string): string { return value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character]!); }
function messageFor(error: unknown): string { return error instanceof AdminApiError ? `${error.status}${error.code === undefined ? "" : ` · ${error.code}`}` : error instanceof Error ? error.message : "未知错误"; }
