import type { RouterRunDetail, RouterRunPage } from "../../../../src/shared/contracts.ts";
import { emptyRow, escape, formatTime, statusPill } from "../page-helpers.ts";
import type { PageRenderContext } from "../page-context.ts";

export function renderTracesPage({ state }: PageRenderContext): string {
  const page = state.runs;
  return `<section class="run-operations run-tracking-page"><article class="panel run-list-panel"><div class="panel-title"><div><p>当前 Run 列表</p><span>按更新时间分页；状态与结果只来自 Router/Runtime 的持久化投影。用户产物仅保留数量，不展示隐私元数据。</span></div><span class="count">${page.total}</span></div><div class="table-wrap"><table><thead><tr><th>用户指令</th><th>状态</th><th>Runtime</th><th>计划</th><th>结果</th><th>更新时间</th></tr></thead><tbody>${page.items.length === 0 ? emptyRow(6, "暂无 Run") : page.items.map((run) => runRow(run, state.runDetail?.id === run.id)).join("")}</tbody></table></div><div class="pagination"><button class="ghost" data-action="run-page-prev" ${page.page <= 1 ? "disabled" : ""}>上一页</button><span>第 ${page.page} / ${page.pageCount} 页 · 共 ${page.total} 个</span><button class="ghost" data-action="run-page-next" ${page.page >= page.pageCount ? "disabled" : ""}>下一页</button></div></article>${state.runDetail === undefined ? "" : `<div class="dialog-backdrop"><article class="dialog run-detail-dialog"><button class="dialog-close" data-action="close-run-detail" aria-label="关闭">×</button>${runDetailView(state.runDetail)}</article></div>`}</section>`;
}

function runRow(run: RouterRunPage["items"][number], selected: boolean): string { const input = run.input === undefined ? "（严格本地输入未在 Router 保存）" : run.input; const result = run.status === "failed" ? (run.errorMessage ?? run.errorCode ?? "失败") : (run.output ?? "—"); return `<tr class="run-row${selected ? " selected" : ""}" data-run-id="${escape(run.id)}"><td><strong>${escape(input.slice(0, 80))}</strong><small>${escape(run.id)}</small></td><td>${statusPill(run.status)}</td><td>${escape(run.runtimeName ?? run.runtimeId ?? "—")}<small>${escape(run.modelKey ?? "")}</small></td><td>${run.planStepCount === undefined ? "—" : `${run.planStepCount} 步`}<small>${escape(run.planState ?? "")}</small></td><td><span class="run-result">${escape(result.slice(0, 80))}</span><small>${run.artifactCount === undefined ? "" : `${run.artifactCount} 个产物`}</small></td><td>${formatTime(run.updatedAt)}</td></tr>`; }

function runDetailView(run: RouterRunDetail): string {
  const plan = run.plan;
  const outcome = run.outcome;
  return `<div class="run-detail-head"><div><p class="panel-kicker">RUN OPERATIONS</p><h2>${escape(run.id)}</h2><p>${escape(run.input ?? "严格本地输入未在 Router 保存")}</p></div>${statusPill(run.status)}</div><div class="run-facts"><span><b>Runtime</b>${escape(run.runtimeName ?? run.runtimeId ?? "—")}</span><span><b>模型</b>${escape(run.modelKey ?? "—")}</span><span><b>创建</b>${formatTime(run.createdAt)}</span><span><b>更新</b>${formatTime(run.updatedAt)}</span></div><section class="skill-section"><div class="skill-section-title"><h3>Plan / 计划步骤</h3><span>${plan === undefined ? "Runtime 边界不可用" : `${plan.steps.length} 步 · ${escape(plan.status)}`}</span></div>${plan === undefined ? `<p class="muted-text">未能读取 Host canonical Plan。</p>` : `<p>${escape(plan.goal)}</p><div class="run-steps">${plan.steps.map((step, index) => `<div class="run-step"><b>${index + 1}. ${escape(step.objective)}</b><span>${statusPill(step.status)}</span>${step.output === undefined ? "" : `<p>${escape(step.output)}</p>`}${step.error === undefined ? "" : `<p class="danger-text">${escape(step.error)}</p>`}</div>`).join("")}</div>`}</section><section class="skill-section"><div class="skill-section-title"><h3>Canonical Outcome</h3><span>${outcome === undefined ? "未读取" : escape(outcome.reasonCode)}</span></div>${outcome === undefined ? `<p class="muted-text">Outcome 不可用；不能据此推断任务成功。</p>` : `<div class="outcome-card ${outcome.status === "completed" ? "success" : "failed"}"><strong>${escape(outcome.status)}</strong><p>${escape(outcome.output ?? run.output ?? run.errorMessage ?? "")}</p><small>提交时间 ${formatTime(outcome.committedAt)}</small></div>`}</section><section class="skill-section"><div class="skill-section-title"><h3>产物</h3><span>${run.artifacts.length} 个</span></div>${run.artifacts.length === 0 ? `<p class="muted-text">暂无已确认产物。</p>` : `<ul class="artifact-list">${run.artifacts.map((artifact) => `<li><strong>${escape(artifact.name)}</strong><small>${escape(artifact.mimeType)} · ${artifact.bytes} bytes</small></li>`).join("")}</ul>`}</section>${run.missingBoundaries.length === 0 ? "" : `<div class="boundary-warning"><b>缺失边界</b><span>${run.missingBoundaries.map((item) => escape(item)).join("、")}</span></div>`}</div>`;
}
