import type { AdminMember, AdminMemberRole, AdminUser, AdminUserStatus } from "../../../../control-plane/contracts/index.ts";
import type { BusinessUserSummary } from "../../shared/api/admin-api-client.ts";
import { emptyRow, escape, formatTime, permissionNote, statusPill } from "../page-helpers.ts";
import type { PageRenderContext } from "../page-context.ts";

export function renderAdminUsersPage({ state, can }: PageRenderContext): string {
  const page = adminUserPage(state.users, state.userPage, state.userPageSize);
  return `<section class="members-page"><article class="panel wide"><div class="panel-title"><div><p>管理端用户</p><span>这里管理 Admin API 自己的登录用户、角色和状态，不管理 Multi Runtime 的使用用户。</span></div><div class="panel-actions"><span class="count">${state.users.length}</span>${can("user.write") ? `<button class="primary" data-action="new-user">新增用户</button>` : ""}</div></div><div class="table-wrap"><table><thead><tr><th>用户</th><th>角色</th><th>Scope</th><th>状态</th><th>更新时间</th><th></th></tr></thead><tbody>${state.users.length === 0 ? emptyRow(6, "暂无管理端用户") : page.items.map(adminUserRow).join("")}</tbody></table></div><div class="pagination admin-user-pagination"><button class="ghost" data-action="admin-user-page-prev" ${page.page <= 1 ? "disabled" : ""}>上一页</button><span>第 ${page.page} / ${page.pageCount} 页 · 共 ${state.users.length} 个</span><button class="ghost" data-action="admin-user-page-next" ${page.page >= page.pageCount ? "disabled" : ""}>下一页</button></div></article>${can("user.write") && state.userModal ? adminUserForm(state.users, state.userEditingId) : ""}${!can("user.write") ? permissionNote("当前角色没有 user.write，无法管理 Admin 用户。") : ""}</section>`;
}

export function renderBusinessUsersPage({ state, can }: PageRenderContext): string {
  const page = state.businessUsers;
  return `<section class="members-page"><article class="panel wide"><div class="panel-title"><div><p>AgentLoop 业务用户</p><span>用户资料、状态和活动时间均来自 Router；Token 消耗账本尚未接入，不做估算。</span></div><span class="count">${page.total}</span></div><div class="table-wrap"><table><thead><tr><th>邮箱</th><th>Tenant</th><th>状态</th><th>创建时间</th><th>最新活动</th><th>Token 消耗</th><th></th></tr></thead><tbody>${page.items.length === 0 ? emptyRow(7, "暂无业务用户") : page.items.map((user) => businessUserRow(user, can("user.write"))).join("")}</tbody></table></div><div class="pagination"><button class="ghost" data-action="business-user-prev" ${page.page <= 1 ? "disabled" : ""}>上一页</button><span>第 ${page.page} / ${page.pageCount} 页 · 共 ${page.total} 个</span><button class="ghost" data-action="business-user-next" ${page.page >= page.pageCount ? "disabled" : ""}>下一页</button></div></article>${state.businessUserPasswordId === undefined ? "" : businessPasswordForm()}</section>`;
}

export function renderRuntimeMembersForm(scopeId: string): string {
  return `<article class="panel form-panel"><div class="panel-title"><div><p>添加成员</p><span>角色是管理端权限的来源，不绑定 Router 用户会话。</span></div></div><form id="member-form" class="form-grid"><label>Subject<input name="subject" required placeholder="例如 ops@example.com"></label><label>显示名称<input name="displayName" required placeholder="例如 运维同学"></label><label>Scope ID<input name="scopeId" value="${escape(scopeId)}" required></label><label>角色<select name="role">${roleOptions()}</select></label><button class="primary span-2" type="submit">创建成员</button></form></article>`;
}

function adminUserPage(users: readonly AdminUser[], requestedPage: number, pageSize: number): { readonly items: readonly AdminUser[]; readonly page: number; readonly pageCount: number } { const pageCount = Math.max(1, Math.ceil(users.length / pageSize)); const page = Math.min(Math.max(1, requestedPage), pageCount); return { items: users.slice((page - 1) * pageSize, page * pageSize), page, pageCount }; }
function adminUserRow(user: AdminUser): string { const next: AdminUserStatus | undefined = user.status === "active" ? "suspended" : user.status === "suspended" ? "active" : undefined; return `<tr><td><strong>${escape(user.displayName)}</strong><small>${escape(user.username)} · ${escape(user.userId)}</small></td><td><span class="tag purple">${escape(user.role)}</span></td><td>${escape(user.scopeId ?? "平台")}</td><td>${statusPill(user.status)}<small>rev ${user.revision}</small></td><td>${formatTime(user.updatedAt)}</td><td class="actions"><button class="text-button" data-user-edit="${escape(user.userId)}">编辑</button>${next === undefined ? "" : `<button class="text-button" data-user-transition="${escape(user.userId)}" data-user-status="${next}" data-user-revision="${user.revision}">${next === "active" ? "启用" : "停用"}</button>`}</td></tr>`; }
function adminUserForm(users: readonly AdminUser[], editingId?: string): string { const editing = editingId === undefined ? undefined : users.find((user) => user.userId === editingId); return `<div class="dialog-backdrop"><article class="dialog admin-user-dialog"><button class="dialog-close" data-action="cancel-user-edit" aria-label="关闭">×</button><p class="eyebrow">ADMIN USER</p><h2>${editing === undefined ? "新增管理端用户" : "编辑管理端用户"}</h2><p>密码只提交给 Admin API，数据库仅保存 scrypt hash。</p><form id="admin-user-form" class="form-grid"><label>用户名<input name="username" value="${escape(editing?.username ?? "")}" ${editing === undefined ? "" : "readonly"} required placeholder="例如 ops@example.com"></label><label>显示名称<input name="displayName" value="${escape(editing?.displayName ?? "")}" required></label><label>Scope ID<input name="scopeId" value="${escape(editing?.scopeId ?? "")}" placeholder="留空表示平台范围"></label><label>角色<select name="role">${roleOptions(editing?.role)}</select></label><label class="span-2">${editing === undefined ? "初始密码" : "重置密码（留空不修改）"}<input name="password" type="password" ${editing === undefined ? "required" : ""} minlength="12" placeholder="至少 12 个字符"></label><div class="button-row span-2"><button class="primary" type="submit">${editing === undefined ? "创建用户" : "保存用户"}</button><button class="secondary" type="button" data-action="cancel-user-edit">取消</button></div></form></article></div>`; }
function businessUserRow(user: BusinessUserSummary, writable: boolean): string { return `<tr><td><strong>${escape(user.email)}</strong><small>${escape(user.id)}</small></td><td><code>${escape(user.tenantId)}</code></td><td>${statusPill(user.status)}</td><td>${formatTime(user.createdAt)}</td><td>${user.lastActiveAt === undefined ? "暂无活动" : formatTime(user.lastActiveAt)}</td><td><span class="muted-text">暂无消费数据</span></td><td class="actions">${writable ? `${user.status === "active" ? `<button class="text-button danger-link" data-business-suspend="${escape(user.id)}">停用</button>` : ""}<button class="text-button" data-business-password="${escape(user.id)}">重置密码</button>` : ""}</td></tr>`; }
function businessPasswordForm(): string { return `<div class="dialog-backdrop"><article class="dialog"><button class="dialog-close" data-action="cancel-business-password" aria-label="关闭">×</button><p class="eyebrow">BUSINESS USER</p><h2>重置密码</h2><p>新密码只提交给 Router，Router 不返回密码或密码哈希。</p><form id="business-password-form" class="form-grid"><label class="span-2">新密码<input name="password" type="password" minlength="12" required></label><div class="button-row span-2"><button class="primary" type="submit">确认重置</button><button class="secondary" type="button" data-action="cancel-business-password">取消</button></div></form></article></div>`; }
function memberRow(member: AdminMember, writable: boolean): string { const next = member.status === "active" ? "suspended" : member.status === "suspended" || member.status === "invited" ? "active" : undefined; return `<tr><td><strong>${escape(member.displayName)}</strong><small>${escape(member.subject)}</small></td><td><span class="tag">${escape(member.role)}</span></td><td>${statusPill(member.status)}</td><td>${member.revision}</td><td class="actions">${writable && next !== undefined ? `<button class="text-button" data-member-transition="${escape(member.memberId)}" data-member-state="${next}" data-member-revision="${member.revision}">${next === "active" ? "启用" : "暂停"}</button>` : ""}</td></tr>`; }
function roleOptions(selected?: AdminMemberRole): string { return (["platform_admin", "operator", "skill_operator", "auditor", "member"] as const).map((role) => `<option value="${role}" ${selected === role ? "selected" : ""}>${role}</option>`).join(""); }
