import { createHash } from "node:crypto";
import type { SqlConnection } from "@zhujun/agentloop";

export interface ExecutableControlPlaneMigration {
  readonly id: string;
  readonly definition: string;
  readonly apply: (database: SqlConnection) => Promise<void>;
}

export class ControlPlaneMigrationError extends Error {
  public constructor(message: string) {
    super(message);
    this.name = "ControlPlaneMigrationError";
  }
}

const migrations: readonly ExecutableControlPlaneMigration[] = [{
  id: "control-plane/0001_resources_releases_assignments_receipts_audit",
  definition: "cp_schema_migrations;cp_resources;cp_releases;cp_target_assignments;cp_apply_receipts;cp_integration_bindings;cp_skill_artifacts;cp_secret_references;cp_audit_events;cp_delivery_cursors:v1",
  apply: async (database) => { await database.exec(controlPlaneSchemaSql(database.dialect)); },
}, {
  id: "control-plane/0002_configuration_revision_sequence",
  definition: "cp_configuration_revision_sequence:v1",
  apply: async (database) => { await database.exec(configurationRevisionSequenceSql(database.dialect)); },
}];

/** Standalone migration entry point. No Router, Host, or Admin API startup code calls this. */
export async function migrateControlPlane(database: SqlConnection): Promise<void> {
  await database.exec(controlPlaneMigrationLedgerSql(database));
  await withMigrationLock(database, async () => {
    for (const migration of migrations) {
      const checksum = checksumFor(migration);
      const applied = await database.prepare("SELECT checksum FROM cp_schema_migrations WHERE id = ?").get<{ checksum: string }>(migration.id);
      if (applied !== undefined) {
        if (applied.checksum !== checksum) {
          throw new ControlPlaneMigrationError(`Migration checksum mismatch for ${migration.id}; refusing to run against unknown control-plane history`);
        }
        continue;
      }
      await migration.apply(database);
      await database.prepare("INSERT INTO cp_schema_migrations(id, checksum, applied_at) VALUES (?, ?, ?)").run(migration.id, checksum, Date.now());
    }
  });
}

export function controlPlaneMigrationIds(): readonly string[] {
  return migrations.map((migration) => migration.id);
}

/** Startup readiness check only. It never creates the ledger or any cp_* table. */
export async function assertControlPlaneMigrationsReady(database: SqlConnection): Promise<void> {
  for (const migration of migrations) {
    let applied: { checksum: string } | undefined;
    try {
      applied = await database.prepare("SELECT checksum FROM cp_schema_migrations WHERE id = ?").get<{ checksum: string }>(migration.id);
    } catch {
      throw new ControlPlaneMigrationError("Control-plane migration ledger is unavailable; run the standalone migration job first");
    }
    if (applied?.checksum !== checksumFor(migration)) {
      throw new ControlPlaneMigrationError(`Control-plane migration ${migration.id} is missing or has an unexpected checksum`);
    }
  }
}

export function controlPlaneMigrationLedgerSql(database: Pick<SqlConnection, "dialect">): string {
  return database.dialect === "tidb"
    ? "CREATE TABLE IF NOT EXISTS cp_schema_migrations (id VARCHAR(191) PRIMARY KEY, checksum CHAR(64) NOT NULL, applied_at BIGINT NOT NULL)"
    : database.dialect === "postgres"
      ? "CREATE TABLE IF NOT EXISTS cp_schema_migrations (id TEXT PRIMARY KEY, checksum TEXT NOT NULL, applied_at BIGINT NOT NULL)"
      : "CREATE TABLE IF NOT EXISTS cp_schema_migrations (id TEXT PRIMARY KEY, checksum TEXT NOT NULL, applied_at INTEGER NOT NULL)";
}

/** Source-level SQL by dialect; TiDB is never generated by translating PostgreSQL. */
export function controlPlaneSchemaSql(dialect: SqlConnection["dialect"]): string {
  if (dialect === "tidb") return tidbSchemaSql();
  const text = dialect === "postgres" ? "TEXT" : "TEXT";
  const epoch = dialect === "postgres" ? "BIGINT" : "INTEGER";
  return String.raw`CREATE TABLE IF NOT EXISTS cp_resources (
    id ${text} PRIMARY KEY, kind ${text} NOT NULL, owner_tenant_id ${text}, revision ${epoch} NOT NULL,
    created_at ${epoch} NOT NULL, updated_at ${epoch} NOT NULL
  );
  CREATE TABLE IF NOT EXISTS cp_releases (
    id ${text} PRIMARY KEY, resource_id ${text} NOT NULL, version ${epoch} NOT NULL, kind ${text} NOT NULL,
    schema_version ${text} NOT NULL, content_hash ${text} NOT NULL, author_id ${text} NOT NULL, created_at ${epoch} NOT NULL,
    state ${text} NOT NULL, payload_json ${text} NOT NULL, UNIQUE(resource_id, version)
  );
  CREATE TABLE IF NOT EXISTS cp_target_assignments (
    id ${text} PRIMARY KEY, resource_id ${text} NOT NULL, release_id ${text} NOT NULL, plane ${text} NOT NULL,
    target_kind ${text} NOT NULL, tenant_id ${text}, runtime_class ${text}, runtime_id ${text}, device_id ${text},
    priority ${epoch} NOT NULL, rollout_state ${text} NOT NULL, revision ${epoch} NOT NULL, created_at ${epoch} NOT NULL, updated_at ${epoch} NOT NULL
  );
  CREATE INDEX IF NOT EXISTS cp_target_assignments_resource_idx ON cp_target_assignments(resource_id, rollout_state, priority);
  CREATE TABLE IF NOT EXISTS cp_apply_receipts (
    id ${text} PRIMARY KEY, target_plane ${text} NOT NULL, tenant_id ${text} NOT NULL, runtime_id ${text} NOT NULL,
    device_id ${text}, release_id ${text} NOT NULL, content_hash ${text} NOT NULL, status ${text} NOT NULL,
    reason_code ${text}, observed_at ${epoch} NOT NULL
  );
  CREATE INDEX IF NOT EXISTS cp_apply_receipts_target_idx ON cp_apply_receipts(target_plane, tenant_id, runtime_id, observed_at);
  CREATE TABLE IF NOT EXISTS cp_integration_bindings (
    id ${text} PRIMARY KEY, release_id ${text} NOT NULL, credential_reference_id ${text}, scope_json ${text} NOT NULL,
    egress_policy_json ${text} NOT NULL, created_at ${epoch} NOT NULL
  );
  CREATE TABLE IF NOT EXISTS cp_skill_artifacts (
    release_id ${text} PRIMARY KEY, package_uri ${text} NOT NULL, package_hash ${text} NOT NULL, signer ${text} NOT NULL,
    compatibility_json ${text} NOT NULL, created_at ${epoch} NOT NULL
  );
  CREATE TABLE IF NOT EXISTS cp_secret_references (
    id ${text} PRIMARY KEY, provider ${text} NOT NULL, secret_key ${text} NOT NULL, secret_version ${text} NOT NULL,
    rotation_state ${text} NOT NULL, created_at ${epoch} NOT NULL, updated_at ${epoch} NOT NULL
  );
  CREATE TABLE IF NOT EXISTS cp_audit_events (
    id ${text} PRIMARY KEY, actor_id ${text} NOT NULL, action ${text} NOT NULL, resource_id ${text} NOT NULL,
    release_id ${text}, before_ref ${text}, after_ref ${text}, created_at ${epoch} NOT NULL
  );
  CREATE INDEX IF NOT EXISTS cp_audit_events_resource_idx ON cp_audit_events(resource_id, created_at);
  CREATE TABLE IF NOT EXISTS cp_delivery_cursors (
    target_plane ${text} NOT NULL, tenant_id ${text} NOT NULL, runtime_id ${text} NOT NULL, device_id ${text},
    revision ${epoch} NOT NULL, idempotency_key ${text} NOT NULL, updated_at ${epoch} NOT NULL,
    PRIMARY KEY(target_plane, tenant_id, runtime_id)
  );`;
}

function configurationRevisionSequenceSql(dialect: SqlConnection["dialect"]): string {
  if (dialect === "tidb") return String.raw`CREATE TABLE IF NOT EXISTS cp_configuration_revision_sequence (
    id BIGINT PRIMARY KEY, revision BIGINT NOT NULL
  );
  INSERT IGNORE INTO cp_configuration_revision_sequence(id, revision) VALUES (1, 0);`;
  if (dialect === "postgres") return String.raw`CREATE TABLE IF NOT EXISTS cp_configuration_revision_sequence (
    id BIGINT PRIMARY KEY, revision BIGINT NOT NULL
  );
  INSERT INTO cp_configuration_revision_sequence(id, revision) VALUES (1, 0) ON CONFLICT (id) DO NOTHING;`;
  return String.raw`CREATE TABLE IF NOT EXISTS cp_configuration_revision_sequence (
    id INTEGER PRIMARY KEY, revision INTEGER NOT NULL
  );
  INSERT OR IGNORE INTO cp_configuration_revision_sequence(id, revision) VALUES (1, 0);`;
}

function tidbSchemaSql(): string {
  return String.raw`CREATE TABLE IF NOT EXISTS cp_resources (
    id VARCHAR(191) PRIMARY KEY, kind VARCHAR(64) NOT NULL, owner_tenant_id VARCHAR(191), revision BIGINT NOT NULL,
    created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL
  );
  CREATE TABLE IF NOT EXISTS cp_releases (
    id VARCHAR(191) PRIMARY KEY, resource_id VARCHAR(191) NOT NULL, version BIGINT NOT NULL, kind VARCHAR(64) NOT NULL,
    schema_version VARCHAR(191) NOT NULL, content_hash CHAR(64) NOT NULL, author_id VARCHAR(191) NOT NULL, created_at BIGINT NOT NULL,
    state VARCHAR(32) NOT NULL, payload_json LONGTEXT NOT NULL, UNIQUE KEY cp_releases_resource_version_uq(resource_id, version)
  );
  CREATE TABLE IF NOT EXISTS cp_target_assignments (
    id VARCHAR(191) PRIMARY KEY, resource_id VARCHAR(191) NOT NULL, release_id VARCHAR(191) NOT NULL, plane VARCHAR(8) NOT NULL,
    target_kind VARCHAR(32) NOT NULL, tenant_id VARCHAR(191), runtime_class VARCHAR(191), runtime_id VARCHAR(191), device_id VARCHAR(191),
    priority BIGINT NOT NULL, rollout_state VARCHAR(32) NOT NULL, revision BIGINT NOT NULL, created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL
  );
  CREATE INDEX IF NOT EXISTS cp_target_assignments_resource_idx ON cp_target_assignments(resource_id, rollout_state, priority);
  CREATE TABLE IF NOT EXISTS cp_apply_receipts (
    id VARCHAR(191) PRIMARY KEY, target_plane VARCHAR(8) NOT NULL, tenant_id VARCHAR(191) NOT NULL, runtime_id VARCHAR(191) NOT NULL,
    device_id VARCHAR(191), release_id VARCHAR(191) NOT NULL, content_hash CHAR(64) NOT NULL, status VARCHAR(32) NOT NULL,
    reason_code VARCHAR(64), observed_at BIGINT NOT NULL
  );
  CREATE INDEX IF NOT EXISTS cp_apply_receipts_target_idx ON cp_apply_receipts(target_plane, tenant_id, runtime_id, observed_at);
  CREATE TABLE IF NOT EXISTS cp_integration_bindings (
    id VARCHAR(191) PRIMARY KEY, release_id VARCHAR(191) NOT NULL, credential_reference_id VARCHAR(191), scope_json LONGTEXT NOT NULL,
    egress_policy_json LONGTEXT NOT NULL, created_at BIGINT NOT NULL
  );
  CREATE TABLE IF NOT EXISTS cp_skill_artifacts (
    release_id VARCHAR(191) PRIMARY KEY, package_uri LONGTEXT NOT NULL, package_hash CHAR(64) NOT NULL, signer VARCHAR(191) NOT NULL,
    compatibility_json LONGTEXT NOT NULL, created_at BIGINT NOT NULL
  );
  CREATE TABLE IF NOT EXISTS cp_secret_references (
    id VARCHAR(191) PRIMARY KEY, provider VARCHAR(191) NOT NULL, secret_key VARCHAR(191) NOT NULL, secret_version VARCHAR(191) NOT NULL,
    rotation_state VARCHAR(32) NOT NULL, created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL
  );
  CREATE TABLE IF NOT EXISTS cp_audit_events (
    id VARCHAR(191) PRIMARY KEY, actor_id VARCHAR(191) NOT NULL, action VARCHAR(64) NOT NULL, resource_id VARCHAR(191) NOT NULL,
    release_id VARCHAR(191), before_ref VARCHAR(191), after_ref VARCHAR(191), created_at BIGINT NOT NULL
  );
  CREATE INDEX IF NOT EXISTS cp_audit_events_resource_idx ON cp_audit_events(resource_id, created_at);
  CREATE TABLE IF NOT EXISTS cp_delivery_cursors (
    target_plane VARCHAR(8) NOT NULL, tenant_id VARCHAR(191) NOT NULL, runtime_id VARCHAR(191) NOT NULL, device_id VARCHAR(191),
    revision BIGINT NOT NULL, idempotency_key VARCHAR(191) NOT NULL, updated_at BIGINT NOT NULL,
    PRIMARY KEY(target_plane, tenant_id, runtime_id)
  );`;
}

async function withMigrationLock(database: SqlConnection, operation: () => Promise<void>): Promise<void> {
  if (database.dialect === "sqlite") return await database.transaction(operation);
  if (database.dialect === "postgres") {
    return await database.transaction(async () => {
      await database.prepare("SELECT pg_advisory_xact_lock(hashtext(?))").get("agentloop:control-plane:schema");
      await operation();
    });
  }
  const lock = await database.prepare("SELECT GET_LOCK(?, 60) AS acquired").get<{ acquired: number | string | null }>("agentloop:control-plane:schema");
  if (Number(lock?.acquired) !== 1) throw new ControlPlaneMigrationError("Timed out acquiring TiDB control-plane migration lock");
  try { await operation(); } finally { await database.prepare("SELECT RELEASE_LOCK(?)").get("agentloop:control-plane:schema"); }
}

function checksumFor(migration: ExecutableControlPlaneMigration): string {
  return createHash("sha256").update(`${migration.id}\n${migration.definition}`).digest("hex");
}
